- type: entity
  parent: BaseMindRoleAntag
  id: RRMindRoleCriminal
  name: Criminal Role
  components:
  - type: MindRole
    exclusiveAntag: true
    subtype: rr-criminal
  
- type: entity
  id: RRMindRoleDeserter
  name: Deserter Role
  components:
  - type: MindRole
    roleType: HarmlessAntagonist
    subtype: rr-war-deserter
    antag: true
    antagPrototype: RRMindRoleDeserter
    sortWeight: 40