- type: dungeonConfig
  id: SyndieDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SyndieDungeon
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorDunGen
    width: 5
    tile: FloorShuttleRed

  - !type:DungeonEntranceDunGen
    count: 5
    tile: FloorShuttleRed
    contents: SyndieDungeonEntrance

  - !type:RoomEntranceDunGen
    tile: FloorShuttleRed
    contents: SyndieDungeonEntrance

  - !type:EntranceFlankDunGen
    tile: FloorShuttleRed
    contents: SyndieDungeonWindow

  - !type:WallMountDunGen
    tile: FloorShuttleRed
    contents: SyndieDungeonWalls

  - !type:BoundaryWallDunGen
    tile: FloorShuttleRed
    wall: WallReinforced
    cornerWall: WallReinforced

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entityTable
  id: SyndieDungeonEntrance
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: AirlockSyndicateLocked

- type: entityTable
  id: SyndieDungeonWindow
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WallBrick
    - id: LandMineExplosive
    - id: PoweredSmallLight

- type: entityTable
  id: SyndieDungeonWalls
  table: !type:GroupSelector
    children:
    # Posters
    - id: PosterContrabandEnlistGorlex
    - id: PosterLegitEnlist
    - id: PosterContrabandFreeDrone
    - id: PosterContrabandFreeSyndicateEncryptionKey
    - id: PosterContrabandSyndicatePistol

#========================================================================
- type: dungeonConfig
  id: ShipWreckDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - ShipWreck
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

#========================================================================   

# type: dungeonConfig
# id: NoWallArenaPlanetBase
# layers:
# - !type:PrefabDunGen
#   presets:
#   - Arena
#   
# - !type:CorridorDunGen
#   width: 1
#
# - !type:DungeonEntranceDunGen
#   count: 1
#
# - !type:RoomEntranceDunGen
#
# - !type:EntranceFlankDunGen
#
# - !type:BoundaryWallDunGen
#
# - !type:JunctionDunGen
#   width: 1
#
# - !type:JunctionDunGen
#
# - !type:CornerClutterDunGen

#- type: dungeonConfig
#  id: ElderArenaDungeon
#  data:
#    tiles:
#      FallbackTile: FloorAbyss
#    spawnGroups:
#      Window: Nothing
#    whitelists:
#      Rooms:
#        tags:
#        - ElderArena
#  layers:
#  - !type:PrototypeDunGen
#    proto: NoWallArenaPlanetBase

#========================================================================   
- type: dungeonConfig
  id: SovietDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SovietDungeonWeh
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorDunGen
    width: 5
    tile: FloorConcreteMono

  - !type:DungeonEntranceDunGen
    count: 5
    tile: FloorConcreteMono
    contents: SovietDungeonEntrance

  - !type:RoomEntranceDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonRoomEntrance

  - !type:EntranceFlankDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWindow

  - !type:WallMountDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWalls

  - !type:BoundaryWallDunGen
    tile: FloorConcreteMono
    wall: WallBrick
    cornerWall: WallBrick

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entityTable
  id: SovietDungeonEntrance
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: MetalDoor

- type: entityTable
  id: SovietDungeonRoomEntrance
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WoodDoor

- type: entityTable
  id: SovietDungeonWindow
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WallBrick
    - id: PoweredSmallLight

- type: entityTable
  id: SovietDungeonWalls
  table: !type:GroupSelector
    children:
    # Posters
    - id: PosterContrabandCommunistState
    - id: PosterContrabandPunchShit
    - id: PosterContrabandRevolt
    - id: PosterContrabandRise
    - id: PosterLegitWorkForAFuture


#========================================================================   
- type: dungeonConfig
  id: SovietDungeonWeh
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SovietDungeon
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorDunGen
    width: 3
    tile: FloorTechMaint3

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorTechMaint2
    contents: SovietDungeonEntranceWeh

  - !type:RoomEntranceDunGen
    tile: FloorTechMaint3
    contents: SovietDungeonRoomEntranceWeh

  - !type:EntranceFlankDunGen
    tile: FloorTechMaint3
    contents: SovietDungeonWindowWeh

  - !type:WallMountDunGen
    tile: FloorTechMaint3
    contents: SovietDungeonWallsWeh

  - !type:BoundaryWallDunGen
    tile: FloorTechMaint3
    wall: WallSolidRust
    cornerWall: WallSolidRust

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorClutterDunGen
    contents: SovietCorridorsWeh
    chance: 0.55

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: GrayConcreteTrimLineS
      East: GrayConcreteTrimLineE
      North: GrayConcreteTrimLineN
      West: GrayConcreteTrimLineW
    cornerDecals:
      SouthEast: GrayConcreteTrimCornerSe
      SouthWest: GrayConcreteTrimCornerSw
      NorthEast: GrayConcreteTrimCornerNe
      NorthWest: GrayConcreteTrimCornerNw
    pocketDecals:
      SouthWest: GrayConcreteTrimInnerSw
      SouthEast: GrayConcreteTrimInnerSe
      NorthWest: GrayConcreteTrimInnerNw
      NorthEast: GrayConcreteTrimInnerNe

- type: entityTable
  id: SovietDungeonEntranceWeh
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: AirlockHatch

- type: entityTable
  id: SovietDungeonRoomEntranceWeh
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: AirlockHatch

- type: entityTable
  id: SovietDungeonWindowWeh
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WallSolidRust
    - id: PoweredSmallLight

- type: entityTable
  id: SovietDungeonWallsWeh
  table: !type:GroupSelector
    children:
    # Posters
    - id: PosterContrabandCommunistState
    - id: PosterContrabandPunchShit
    - id: PosterContrabandRevolt
    - id: PosterContrabandRise
    - id: PosterLegitWorkForAFuture

- type: entityTable
  id: SovietCorridorsWeh
  table: !type:GroupSelector
    children:
    # Posters
    - id: VendingMachineSovietSoda
    - id: VendingMachineSovietSodaEmpty
    - id: Rack
      weight: 6
    - id: PoweredLightPostSmall
      weight: 6
    - id: Table
      weight: 6
    - id: BannerSovietRegular
    - id: MobBearSoviet
    - id: DecalSpawnerBloodSplatters
      weight: 6
    - id: GenericTank
      weight: 6
    - id: ClosetRadiationSuitFilled
    - id: ClosetRadiationSuit
    - id: DecalSpawnerDirtWide
      weight: 15
    - id: DecalSpawnerGraffiti
      weight: 15
    - id: RandomSpawner
      weight: 15
    - id: OreBox
      weight: 28
    - id: MaintenancePlantSpawner
      weight: 6
    - id: MaintenanceWeaponSpawner
    - id: MaintenanceToolSpawner
      weight: 6
    - id: RandomMercenaryCorpseSpawner
    - id: RandomSovietCorpseSpawner
    - id: RandomArtifactSpawner20
    - id: SpawnMobOreCrab
    - id: LootSpawnerMedicalMinor
    - id: LootSpawnerMaterialsSupplementary
    - id: SalvageCanisterSpawner
    - id: SalvageSpawnerScrapCommon
    - id: SalvageSpawnerScrapValuable
    - id: SalvageSpawnerTreasure
    - id: SalvageLootSpawner
    - id: BaseBarrelChemRadioactiveFilledUranium
    - id: Bonfire
      weight: 7
    - id: BarrelFlaming
      weight: 3
    - id: AcousticGuitarInstrument
    - id: SovietRevolutionSupplySpawner
    - id: LandMineExplosive
    - id: PuddleBlood
    - id: PuddleVomit
    - id: BarrelChemFilledLube
    - id: BarrelChemEmpty
    - id: BarrelChemFilledPhosphorus
    - id: BarrelChemFilledChlorine



#========================================================================

- type: dungeonConfig
  id: SovietStrategicResourcesWarehouseDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SovietWarehouse
    presets:
    - Arena

  - !type:CorridorDunGen
    width: 5
    tile: FloorConcreteMono

  - !type:DungeonEntranceDunGen
    count: 5
    tile: FloorConcreteMono
    contents: SovietDungeonEntrance

  - !type:RoomEntranceDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonRoomEntrance

  - !type:EntranceFlankDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWindow

  - !type:WallMountDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWalls

  - !type:BoundaryWallDunGen
    tile: FloorConcreteMono
    wall: WallBrick
    cornerWall: WallBrick

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe