using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Shared.CCVar;
using Content.Shared._Starlight.CCVar;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private IAudioManager _audio = default!;
    [Dependency] private IClientAdminManager _admin = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Starlight-start: one sub-tab per group of options instead of one long column.
        AddSection(MusicPage, "ui-options-music-label");
        AddSection(EnvironmentPage, "ui-options-environment-label");
        AddSection(WorldPage, "ui-options-world-label");
        AddSection(VoicesPage, "ui-options-voices-label");
        AddSection(TtsPage, "ui-options-tts-label");
        AddSection(OtherPage, "ui-options-other-label");
        Pages.Orphan();
        CollectSectionButtons();
        // Starlight-end

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));

        // Starlight start

        Control.AddOptionPercentSlider(
            StarlightCCVars.StationRadioVolume,
            SliderMusicRadio,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            StarlightCCVars.TTSVolume,
            SliderTts,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            StarlightCCVars.TTSRadioVolume,
            SliderTtsRadio,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            StarlightCCVars.TTSAnnounceVolume,
            SliderTtsAnnounce,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            StarlightCCVars.TTSChimeVolume,
            SliderTtsChime,
            scale: ContentAudioSystem.TtsMultiplier);

        // Per-category volumes are gain multipliers defaulting to 1, so the slider starts at 50% with room to boost.
        AddCategorySlider(StarlightCCVars.StationHumVolume, SliderStationHum);
        AddCategorySlider(StarlightCCVars.EnvironmentVolume, SliderEnvironment);
        AddCategorySlider(StarlightCCVars.ReverbVolume, SliderReverb);
        AddCategorySlider(StarlightCCVars.EffectsVolume, SliderEffects);
        AddCategorySlider(StarlightCCVars.FootstepsVolume, SliderFootsteps);
        AddCategorySlider(StarlightCCVars.HandlingVolume, SliderHandling);
        AddCategorySlider(StarlightCCVars.CombatVolume, SliderCombat);
        AddCategorySlider(StarlightCCVars.VoiceVolume, SliderVoice);
        AddCategorySlider(StarlightCCVars.AnnouncementVolume, SliderAnnouncement);

        // Starlight end

        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);
        Control.AddOptionCheckBox(StarlightCCVars.RadioChimeMuted, RadioChimeMuteCheckBox);
        Control.AddOptionCheckBox(StarlightCCVars.TTSClientEnabled, TtsClientCheckBox);
        Control.AddOptionCheckBox(StarlightCCVars.TTSRadioQueueEnabled, TtsRadioQueueCheckBox);

        Control.Initialize();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
        RestoreSectionButtons(); // Starlight
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }

    private void UpdateAdminButtonsVisibility()
        => BwoinkSoundCheckBox.Visible = _admin.IsActive(); // Starlight-edit: lambda

    private void OnMasterVolumeSliderChanged(float value)
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        => _audio.SetMasterGain(value); // Starlight-edit: lambda

    #region Starlight
    private void AddSection(Control page, string title)
    {
        page.Orphan();
        page.Margin = new Thickness(4);
        Sections.AddTab(page, Loc.GetString(title));
        _sectionPages.Add(page);
    }

    private readonly List<Control> _sectionPages = [];
    private readonly List<BaseButton> _sectionButtons = [];
    private ButtonGroup? _sectionGroup;

    private void CollectSectionButtons()
    {
        // The first scroll container holds the tab buttons, the second one the pages.
        foreach (var child in Sections.Children)
        {
            if (child is not ScrollContainer)
                continue;

            CollectSectionButtons(child);
            break;
        }
    }

    private void CollectSectionButtons(Control parent)
    {
        foreach (var child in parent.Children)
        {
            if (child is BaseButton { Group: { } group } button)
            {
                _sectionGroup ??= group;
                _sectionButtons.Add(button);
            }
            else
            {
                CollectSectionButtons(child);
            }
        }
    }

    private void RestoreSectionButtons()
    {
        if (_sectionGroup == null)
            return;

        foreach (var button in _sectionButtons)
        {
            button.Group = _sectionGroup;
        }

        for (var i = 0; i < _sectionPages.Count && i < _sectionButtons.Count; i++)
        {
            if (_sectionPages[i].Visible)
                _sectionButtons[i].Pressed = true;
        }
    }

    private void AddCategorySlider(CVarDef<float> cvar, OptionSlider slider)
        => Control.AddOptionPercentSlider(cvar, slider, scale: CategoryVolumeMultiplier);

    private const float CategoryVolumeMultiplier = 2f;

    #endregion
}
