using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Mind;
using Content.Shared._Starlight.Objectives.ObjectivePicker;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Objectives.ObjectivePicker;

[GenerateTypedNameReferences]
public sealed partial class ObjectivePickerWindow : FancyWindow
{
    [Dependency] private IPlayerManager _players = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly SpriteSystem _sprite;
    private readonly SharedMindSystem _mind;

    private float _updateTimer = 1.0f;
    private const float UpdateRate = 1.0f;

    public event Action<NetEntity>? OnSelectedChange;
    public event Action<HashSet<NetEntity>, NetEntity>? OnSubmitted;
    public event Action? OnRandomize;
    public event Action? OnClear;

    public readonly HashSet<NetEntity> SelectedObjectives = [];

    public ObjectivePickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mind = _entity.System<SharedMindSystem>();
        _sprite = _entity.System<SpriteSystem>();

        InitializePicker();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer += args.DeltaSeconds;

        if (_updateTimer >= UpdateRate)
        {
            _updateTimer -= UpdateRate;
            UpdateTimer();
        }
    }

    public void UpdateState()
    {
        _mind.TryGetMind(_players.LocalSession, out var mindUid, out _);
        PopulateObjectives(mindUid);
    }

    public event Action<NetEntity>? OnMulligan;
    public bool Pending { get; private set; }
    public PotentialObjectivesComponent? Offers { get; private set; }
    private readonly Dictionary<NetEntity, Button> _slButtons = new();
    private bool _slSeenMulligan;

    private void InitializePicker()
    {
        SubmitButton.Disabled = true;
        RandomizeButton.Disabled = true;
        MulliganButton.Disabled = true;
        SubmitButton.OnPressed += args =>
        {
            if (_mind.TryGetMind(_players.LocalSession, out var uid, out _))
                OnSubmitted?.Invoke(SelectedObjectives, _entity.GetNetEntity(uid));
        };
        ClearButton.OnPressed += _ => OnClear?.Invoke();
        RandomizeButton.OnPressed += _ => OnRandomize?.Invoke();
        MulliganButton.OnPressed += args =>
        {
            if (_mind.TryGetMind(_players.LocalSession, out var uid, out _))
                OnMulligan?.Invoke(_entity.GetNetEntity(uid));
        };
        UpdateState();
        UpdateTimer();
    }

    public void SetPending(bool pending, string? message = null)
    {
        Pending = pending;
        PickerFeedback.Text = message == null ? string.Empty : Loc.GetString(message);
        UpdateState();
    }

    private void PopulateObjectives(EntityUid mind)
    {
        if (!_entity.TryGetComponent<PotentialObjectivesComponent>(mind, out var offers))
            return;
        Offers = offers;
        if (offers.MulliganUsed && !_slSeenMulligan)
        {
            _slSeenMulligan = true;
            SelectedObjectives.Clear();
            if (offers.RetainedObjective is { } retained)
                SelectedObjectives.Add(retained);
        }
        SelectedObjectives.RemoveWhere(id => !ObjectivePickerSelection.Available(offers, id));

        if (!_slButtons.Keys.ToHashSet().SetEquals(offers.ObjectiveOptions.Keys))
        {
            ObjectiveList.Children.Clear();
            _slButtons.Clear();
            foreach (var (id, info) in offers.ObjectiveOptions)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Children =
                    {
                        new ObjectivePickerRow(_sprite.Frame0(info.Icon), info.Title,
                            offers.Difficulties.GetValueOrDefault(id)),
                    },
                };
                button.OnPressed += _ => OnSelectedChange?.Invoke(id);
                _slButtons[id] = button;
                ObjectiveList.Children.Add(button);
            }
        }

        foreach (var (id, button) in _slButtons)
        {
            var unavailable = !ObjectivePickerSelection.Available(offers, id);
            var conflict = !ObjectivePickerSelection.Compatible(offers, id, SelectedObjectives);
            button.Pressed = SelectedObjectives.Contains(id);
            button.Disabled = Pending || unavailable || conflict;
            button.ToolTip = offers.ObjectiveOptions[id].Description + (unavailable
                ? "\n" + Loc.GetString("objective-picker-option-unavailable")
                : conflict ? "\n" + Loc.GetString("objective-picker-option-conflict") : string.Empty);
        }
        SelectionTip.Text = offers.MinimumDifficulty <= ObjectivePickerSelection.Tolerance
            ? Loc.GetString("objective-picker-window-optional-tip")
            : Loc.GetString("objective-picker-window-difficulty-tip",
            ("selected", ObjectiveDifficultyDisplay.Format(ObjectivePickerSelection.Difficulty(offers, SelectedObjectives))),
            ("minimum", ObjectiveDifficultyDisplay.Format(offers.MinimumDifficulty)));
        if (ObjectivePickerSelection.CanSelectUnderBudget(offers))
            SelectionTip.Text += "\n" + Loc.GetString("objective-picker-under-budget-tip");
        SubmitButton.Disabled = Pending || !ObjectivePickerSelection.Valid(offers, SelectedObjectives);
        ClearButton.Disabled = Pending || SelectedObjectives.Count == 0;
        RandomizeButton.Disabled = Pending || offers.ObjectiveOptions.Count == 0;
        MulliganButton.Disabled = Pending || offers.MulliganUsed || SelectedObjectives.Count != 1;
        MulliganButton.Text = Loc.GetString(offers.MulliganUsed
            ? "objective-picker-window-mulligan-used" : "objective-picker-window-mulligan");
        MulliganButton.ToolTip = Loc.GetString("objective-picker-window-mulligan-tip");
    }

    private void UpdateTimer()
    {
        if (!_mind.TryGetMind(_players.LocalSession, out var uid, out _) ||
            !_entity.TryGetComponent<PotentialObjectivesComponent>(uid, out var offers))
        {
            if (IsOpen)
                Close();
            return;
        }
        PopulateObjectives(uid);
        var left = offers.AutoSelectionTime - _timing.CurTime;
        TimeLeftTip.Text = left <= TimeSpan.Zero
            ? Loc.GetString("objective-picker-window-auto-selecting")
            : Loc.GetString("objective-picker-window-time-left", ("time", left.ToString(@"mm\:ss")));
    }
}
