// Moff - rewrote alot of this file - probably dont accept upstream changes
using Content.Client.Message; // Moffstation
using Content.Shared.Objectives; // Moffstation
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics; // Moffstation
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Objectives.Controls;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveConditionsControl : PanelContainer // Make it button
{
    public ObjectiveConditionsControl()
    {
        RobustXamlLoader.Load(this);
    }

    // Moffstation - Start - Character Menu Redesign
    public ObjectiveConditionsControl(ObjectiveInfo condition, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        ProgressTexture.Texture = sprite.Frame0(condition.Icon);

        ProgressBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2b2c3b") };
        var minColor = Color.Red;
        var maxColor = Color.LimeGreen;
        var fillColor = Color.InterpolateBetween(minColor, maxColor, condition.Progress);
        ProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = fillColor };
        ProgressBar.Value = condition.Progress;

        Title.SetMarkupPermissive(Loc.GetString("objective-title-format", ("title", condition.Title)));
        Description.SetMarkupPermissive(Loc.GetString("objective-description-format",
            ("description", condition.Description)));
    }
    // Moffstation - End
}
