// Moff - rewrote alot of this file - probably dont accept upstream changes
using Content.Shared.Objectives; // Moffstation
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics; // Moffstation
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility; // Moffstation

namespace Content.Client.UserInterface.Systems.Objectives.Controls;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveConditionsControl : PanelContainer // Make it button
{
    public ObjectiveConditionsControl()
    {
        RobustXamlLoader.Load(this);
    }

    // Moffstation - Start - Character Menu Redesign
    public ObjectiveConditionsControl(ObjectiveInfo condition, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        ProgressTexture.Texture = sprite.Frame0(condition.Icon);

        ProgressBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2b2c3b") };
        var minColor = Color.Red;
        var maxColor = Color.LimeGreen;
        var fillColor = Color.InterpolateBetween(minColor, maxColor, condition.Progress);
        ProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = fillColor };
        ProgressBar.Value = condition.Progress;

        var titleMessage = new FormattedMessage();
        titleMessage.AddText(condition.Title);
        titleMessage.PushColor(Color.White);
        Title.SetMessage(titleMessage);

        InfoBox.TooltipSupplier = _ => new Tooltip { Text = condition.Description };
    }
    // Moffstation - End
}
