using System.Linq;
using System.Numerics;
using Content.Shared._FarHorizons.Lobby;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface;

namespace Content.Client._FarHorizons.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class JobPicksWindow : DefaultWindow
{
    // [Dependency] private readonly ISharedFactionManager _factions = default!; // Starlight, no factions.
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private ISharedLobbyManager _lobby = default!;

    private readonly SpriteSystem _sprite;

    public JobPicksWindow()
    {
        Title = Loc.GetString("job-picks-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();

        _lobby.OnJobPicksUpdated += UpdateJobList;
        UpdateJobList();
    }

    private void UpdateJobList()
    {
        #region Starlight
        // Pretty much this entire section is edited since we don't have factions.
        // Only clear our content. Removing the ScrollContainer's children also removes its internal scrollbars.
        JobListContent.RemoveAllChildren();

        var headerContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        JobListContent.AddChild(headerContainer);

        headerContainer.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
            HorizontalExpand = true,
            Children =
            {
                new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = Loc.GetString("job-picks-window-header-job"),
                    HorizontalExpand = true
                }
            }
        });

        headerContainer.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
            Children =
            {
                new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = Loc.GetString("job-picks-window-header-low")
                }
            }
        });

        headerContainer.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
            Children =
            {
                new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = Loc.GetString("job-picks-window-header-medium")
                }
            }
        });

        headerContainer.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
            Children =
            {
                new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = Loc.GetString("job-picks-window-header-high")
                }
            }
        });

        var departments = _protoMan.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .ToList();
        departments.Sort(DepartmentUIComparer.Instance);

        var firstDepartment = true;
        var jobPicks = _lobby.GetJobPicks();
        foreach (var department in departments)
        {
            var jobs = department.Roles
                .Select(job => _protoMan.Index(job))
                .Where(job => job.SetPreference)
                .ToList();
            jobs.Sort(JobUIComparer.Instance);

            if (jobs.Count == 0)
                continue;

            if (firstDepartment)
            {
                firstDepartment = false;
            }
            else
            {
                JobListContent.AddChild(new Control
                {
                    MinSize = new Vector2(0, 23)
                });
            }

            JobListContent.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                HorizontalExpand = true,
                Children =
                {
                    new Label
                    {
                        Margin = new Thickness(5f, 0, 0, 0),
                        Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                            ("departmentName", Loc.GetString(department.Name)))
                    }
                }
            });

            foreach (var job in jobs)
            {
                var jobContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true
                };

                var jobIcon = _protoMan.Index(job.Icon);
                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center,
                    Texture = _sprite.Frame0(jobIcon.Icon)
                };

                var jobLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = job.LocalizedName,
                    HorizontalExpand = true
                };

                if (!jobPicks.TryGetValue(job.ID, out var value))
                    value = (0, 0, 0);

                var lowPrioLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = $" {value.Low}"
                };

                var mediumPrioLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = $" {value.Medium}"
                };

                var highPrioLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = $" {value.High}"
                };

                jobContainer.AddChild(icon);
                jobContainer.AddChild(jobLabel);
                jobContainer.AddChild(lowPrioLabel);
                jobContainer.AddChild(mediumPrioLabel);
                jobContainer.AddChild(highPrioLabel);
                JobListContent.AddChild(jobContainer);
            }
        }
        #endregion
    }
}
