using System.Linq;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class OnlineListWindow : DefaultWindow
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    public OnlineListWindow()
    {
        Title = Loc.GetString("online-list-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _playerManager.PlayerListUpdated += UpdateList;
        UpdateList();

    }

    private void UpdateList()
    {
        var names = _playerManager.Sessions.Select(p => p.Name).ToList().Order();
        OnlineList.Text = string.Join('\n', names);
    }
}