using System.Linq;
using Content.Shared._FarHorizons.Lobby;
using Content.Shared._Starlight.Lobby;
using Content.Shared._NullLink;
using Content.Client.Message;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class OnlineListWindow : DefaultWindow
{
    [Dependency] private ISharedLobbyManager _lobby = default!; // Starlight

    public OnlineListWindow()
    {
        Title = Loc.GetString("online-list-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lobby.OnOnlinePlayersUpdated += UpdateList; // Starlight
        UpdateList();
    }

    private void UpdateList()
    {
        #region Starlight
        // Pretty much had to modify all of this for the groups
        StaffList.SetMarkup(FormatGroup(PlayerTitleCategory.Staff));
        PatronList.SetMarkup(FormatGroup(PlayerTitleCategory.Patron));
        PlayerList.SetMarkup(FormatGroup(PlayerTitleCategory.Player));
    }

    private string FormatGroup(PlayerTitleCategory category)
    {
        var players = _lobby.GetOnlinePlayers()
            .Where(player => player.Category == category)
            .OrderBy(player => player.Name, StringComparer.OrdinalIgnoreCase)
            .Select(FormatPlayer)
            .ToList();

        return players.Count == 0
            ? $"[color=#777777]{Loc.GetString("online-list-window-empty")}[/color]"
            : string.Join('\n', players);
    }

    private static string FormatPlayer(OnlinePlayerInfo player)
    {
        var name = FormattedMessage.EscapeText(player.Name);
        return string.IsNullOrEmpty(player.Title)
            ? name
            : $"{player.Title} {name}";
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _lobby.OnOnlinePlayersUpdated -= UpdateList;

        base.Dispose(disposing);
        #endregion
    }
}
