- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hrs
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 14400 # 4 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Medical
  - External
  - Cryogenics
  - Brigmedic
  - Paramedic
  - Surgery # Starlight
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    ears: ClothingHeadsetBrigmedic
    # neck: ClothingNeckTieRed # Tie variety
    pocket2: HandheldBrigmedicCrewMonitor
    # mask: ClothingMaskBreathMedicalSecurity # Mask variety
    # id: BrigmedicPDA # No longer needed with veteran PDA.
  storage:
    back:
    - Flash
    - SecurityMedkit
    - DefibrillatorBrigmedical

- type: chameleonOutfit
  id: BrigmedicChameleonOutfit
  job: Brigmedic
  equipment:
    mask: ClothingMaskBreathMedicalSecurity
    neck: ClothingNeckTieRed
