using Content.Client.Medical.Cryogenics;
using Content.Shared._Starlight.Plumbing;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingSmartDispenserWindow : DefaultWindow
{
    public PlumbingSmartDispenserWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PlumbingSmartDispenserBuiState state)
    {
        ReagentList.RemoveAllChildren();

        if (state.Entries.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("plumbing-smart-dispenser-empty");
            return;
        }

        var totalVolume = FixedPoint2.Zero;

        foreach (var entry in state.Entries)
        {
            totalVolume += entry.Quantity;

            var chart = new BeakerBarChart
            {
                Capacity = state.MaxPerReagent,
                HorizontalExpand = true,
                MinHeight = 24,
                MaxHeight = 24,
            };

            chart.Clear();
            chart.SetEntry(
                entry.ReagentId,
                Loc.GetString("plumbing-smart-dispenser-reagent-entry",
                    ("reagent", entry.LocalizedName),
                    ("amount", entry.Quantity)),
                entry.Quantity.Float(),
                entry.Color,
                tooltip: $"{entry.LocalizedName}: {entry.Quantity}u / {state.MaxPerReagent}u");

            ReagentList.AddChild(chart);
        }

        StatusLabel.Text = Loc.GetString("plumbing-smart-dispenser-total",
            ("total", totalVolume),
            ("count", state.Entries.Count));
    }
}
