# Ported from Moffstation, but since we have to redo most of it, we have it in our files instead.
- type: antagCategory
  id: Syndicate
  name: antag-category-syndicate-name
  description: antag-category-syndicate-desc
  priority: -1
  accentColor: "#69152e"
  antags:
  - Traitor
  - TraitorSleeper
  - Nukeops
  - NukeopsCommander
  - NukeopsMedic
  - SELFAgent
  - Changeling
  - InitialInfected

- type: antagCategory
  id: Outlaws
  name: antag-category-outlaws-name
  description: antag-category-outlaws-desc
  priority: 2
  accentColor: "#753c2f"
  antags:
  - Brighteye
  - SpaceNinja
  - Thief

- type: antagCategory
  id: USSP
  name: antag-category-ussp-name
  description: antag-category-ussp-desc
  priority: 4
  accentColor: "#cc2500"
  antags:
  - HeadRev

- type: antagCategory
  id: Wizard
  name: antag-category-wizard-name
  description: antag-category-wizard-desc
  priority: 3
  accentColor: "#6b3999"
  antags:
  - Wizard

- type: antagCategory
  id: Xenoborgs
  name: antag-category-xenoborg-name
  description: antag-category-xenoborg-desc
  priority: 5
  accentColor: "#0a0344"
  antags:
  - MothershipCore
  - Xenoborg

- type: antagCategory
  id: Occult
  name: antag-category-occult-name
  description: antag-category-occult-desc
  priority: 1
  accentColor: "#69bbbb"
  antags:
  - CosmicAntagCultist
  - Devil
  - Vampire

- type: antagCategory
  id: Other
  name: antag-category-misc-name
  description: antag-category-misc-desc
  accentColor: "#afa84d"
  priority: 100
  default: true
