- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 30h # You are the sole bodyguard of the highest ranking people on the station, you have to be good.
    - !type:DepartmentTimeRequirement
      department: Command
      time: 25h # You're expected to be mature, at least a little.
    - !type:RoleTimeRequirement
      role: JobBrigmedic
      time: 3h # Lower stakes version of the same role, and forces you to get Paramed time too. Totals to about 8 hours paramed+brigmed combined.
    - !type:RolesRequirement
      proto: ExtRolesReq
  startingGear: BlueShieldGear
  icon: JobIconBlueShield
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Command
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Chemistry
    - Engineering
    - Research
    - Robotics
    - Detective
    - Salvage
    - Security
    - Brigmedic
    - Brig
    - Lawyer
    - Cargo
    - Mail
    - Atmospherics
    - Medical
    - IAA
    - BlueShield
    - Surgery
    - Paramedic
    - Mining
    - SalvageLead
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]

- type: startingGear
  id: BlueShieldGear
  equipment:
    # head: ClothingHeadHatBeretBlueShield
    # id: BlueShieldPDA
    ears: ClothingHeadsetAltBSO # Starlight
    # belt: ClothingBeltBlueShieldWebbingFilled
    pocket1: WeaponPistolSP8T
    pocket2: HandheldBSOCrewMonitor
  storage:
    back:
    - Flash
    - ClothingMaskGasBSO

- type: chameleonOutfit
  id: BlueShieldChameleonOutfit
  job: BlueShield
  equipment:
    head: ClothingHeadHatBeretBlueShield
    gloves: ClothingHandsGlovesCombat
