using Content.Shared._Starlight.Shuttles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class AdjustableThrusterWindow : DefaultWindow
{
    private readonly FloatSpinBox _thrustInput = new(1f, 0) { HorizontalExpand = true };

    public event Action<float>? OnThrustChanged;

    public AdjustableThrusterWindow()
    {
        RobustXamlLoader.Load(this);

        ThrustInputContainer.AddChild(_thrustInput);

        ThrustSlider.Rounded = true;
        ThrustSlider.OnValueChanged += _ =>
        {
            if (!_thrustInput.HasKeyboardFocus())
                _thrustInput.Value = ThrustSlider.Value;
        };
        ThrustSlider.OnReleased += _ => OnThrustChanged?.Invoke(ThrustSlider.Value);

        _thrustInput.OnValueChanged += args =>
        {
            var thrust = Math.Clamp(MathF.Round(args.Value), ThrustSlider.MinValue, ThrustSlider.MaxValue);

            _thrustInput.Value = thrust;
            ThrustSlider.SetValueWithoutEvent(thrust);
            OnThrustChanged?.Invoke(thrust);
        };
    }

    public void UpdateState(AdjustableThrusterBuiState state)
    {
        MinValue.Text = FormatThrust(state.MinThrust);
        MaxValue.Text = FormatThrust(state.MaxThrust);

        ThrustSlider.MinValue = state.MinThrust;
        ThrustSlider.MaxValue = state.MaxThrust;

        if (ThrustSlider.Grabbed || _thrustInput.HasKeyboardFocus())
            return;

        ThrustSlider.SetValueWithoutEvent(state.Thrust);
        _thrustInput.Value = ThrustSlider.Value;
    }

    private static string FormatThrust(float thrust)
        => Loc.GetString("adjustable-thruster-window-output-value", ("thrust", MathF.Round(thrust)));
}
