using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Starlight.Chemistry.UI;

/// <summary>
///     Created by Cookie for multiple servers.
///     Client-side UI used to control a <see cref="SharedChemMaster"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ModernChemMasterWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    public event Action<BaseButton.ButtonEventArgs, ReagentButton>? OnReagentButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, ReagentId, FixedPoint2, bool>? OnCustomReagentButtonPressed;
    public event Action? OnToggleValveButtonPressed;
    public readonly Button[] PillTypeButtons;
    public readonly Button[] PillTypeButtonsClassic;

    private const string PillsRsiPath = "/Textures/Objects/Specific/Chemistry/pills.rsi";

    private ChemMasterBoundUserInterfaceState? _lastState;
    private static bool _classicMode; // Static since if you selected it, you probably want this. Dunno why though.

    private NetEntity? _lastOutputContainer;
    private bool _containerLabelManuallySet;
    private bool _settingContainerLabelProgrammatically;

    private ChemMasterReagentAmount _selectedAmount = ChemMasterReagentAmount.U5;
    private FixedPoint2? _customAmount;
    private bool _customSelected;

    private static readonly Dictionary<NetEntity, (string Text, FixedPoint2? Amount, bool Selected)> _customPerChemMaster = new();
    private NetEntity? _chemMasterNetEntity;

    private readonly Vector2 _modernMinSize; // Window size referenced from MinSize attribute
    private static readonly Vector2 ClassicMinSize = new(666, 670); // We specify the Classic MinSize here since the original value is in an upstream file and it needs to be a bit longer for spacing reasons

    // Amount configs for the 2x5 modern grid: 9 numeric amounts + All.
    private static readonly (string Label, ChemMasterReagentAmount Amount)[] AmountConfigs =
    {
        ("1",   ChemMasterReagentAmount.U1),
        ("5",   ChemMasterReagentAmount.U5),
        ("10",  ChemMasterReagentAmount.U10),
        ("15",  ChemMasterReagentAmount.U15),
        ("20",  ChemMasterReagentAmount.U20),
        ("30",  ChemMasterReagentAmount.U30),
        ("40",  ChemMasterReagentAmount.U40),
        ("60",  ChemMasterReagentAmount.U60),
        ("120", ChemMasterReagentAmount.U120),
        (Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All),
    };

    private static bool IsInCustomAmountRange(string s) => int.TryParse(s, out var v) && v > 0 && v <= 1000;
    private bool IsCustomAmountValid(string s) => !string.IsNullOrWhiteSpace(s) && IsInCustomAmountRange(s);

    /// <summary>
    /// Create and initialize the chem master UI client-side. Creates the basic layout,
    /// actual data isn't filled in until the server sends data about the chem master.
    /// </summary>
    public ModernChemMasterWindow()
    {
        RobustXamlLoader.Load(this);
        _modernMinSize = MinSize; // Captures ModernChemMasterWindow.xaml MinSize
        IoCManager.InjectDependencies(this);
        var sprite = _entityManager.System<SpriteSystem>();

        PillTypeButtons = BuildPillTypeButtons(Grid, sprite);
        PillTypeButtonsClassic = BuildPillTypeButtons(GridClassic, sprite);

        PillDosage.InitDefaultButtons();
        PillNumber.InitDefaultButtons();
        PatchDosage.InitDefaultButtons();
        PatchNumber.InitDefaultButtons();
        BottleDosage.InitDefaultButtons();
        PillDosageClassic.InitDefaultButtons();
        PillNumberClassic.InitDefaultButtons();
        PatchDosageClassic.InitDefaultButtons();
        PatchNumberClassic.InitDefaultButtons();
        BottleDosageClassic.InitDefaultButtons();

        LabelLineEdit.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;
        LabelLineEditClassic.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;

        // container labels use the same maximum length.
        ContainerLabelLineEdit.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;
        ContainerLabelLineEditClassic.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;

        // Keep the normal item label synchronized between modern/classic layouts.
        LabelLineEdit.OnTextChanged += _ =>
        {
            if (LabelLineEditClassic.Text != LabelLineEdit.Text)
                LabelLineEditClassic.Text = LabelLineEdit.Text;
        };

        LabelLineEditClassic.OnTextChanged += _ =>
        {
            if (LabelLineEdit.Text != LabelLineEditClassic.Text)
                LabelLineEdit.Text = LabelLineEditClassic.Text;
        };

        // Keep the separate container label synchronized too, while remembering
        // whether the player has manually overridden the automatic label.
        ContainerLabelLineEdit.OnTextChanged += _ =>
        {
            if (_settingContainerLabelProgrammatically)
                return;

            _containerLabelManuallySet = true;

            _settingContainerLabelProgrammatically = true;
            ContainerLabelLineEditClassic.Text = ContainerLabelLineEdit.Text;
            _settingContainerLabelProgrammatically = false;
        };

        ContainerLabelLineEditClassic.OnTextChanged += _ =>
        {
            if (_settingContainerLabelProgrammatically)
                return;

            _containerLabelManuallySet = true;

            _settingContainerLabelProgrammatically = true;
            ContainerLabelLineEdit.Text = ContainerLabelLineEditClassic.Text;
            _settingContainerLabelProgrammatically = false;
        };

        // Plumbing valve.
        ValveButton.OnPressed += _ => OnToggleValveButtonPressed?.Invoke();
        ValveButtonClassic.OnPressed += _ => OnToggleValveButtonPressed?.Invoke();

        SearchBar.OnTextChanged += _ =>
        {
            SearchBarClassic.Text = SearchBar.Text;
            UpdateReagentPrototypes(SearchBar.Text);
        };

        SearchBarClassic.OnTextChanged += _ =>
        {
            SearchBar.Text = SearchBarClassic.Text;
            UpdateReagentPrototypes(SearchBarClassic.Text);
        };

        ClassicTabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
        ClassicTabs.SetTabTitle(1, Loc.GetString("chem-master-window-output-tab"));

        ModernTabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
        ModernTabs.SetTabTitle(1, Loc.GetString("chem-master-window-output-tab"));

        // Build the amount 'grid' (2x5)
        BuildAmountGrid(AmountGrid);

        // Custom amount - shared validation and per-ChemMaster storage, Modern + Classic textboxes sync
        CustomAmountLineEdit.IsValid = IsInCustomAmountRange;
        CustomAmountLineEditClassic.IsValid = IsInCustomAmountRange;
        CustomAmountLineEdit.OnTextChanged += _ => HandleCustomAmountTextChanged(CustomAmountLineEdit, CustomAmountLineEditClassic, isModern: true);
        CustomAmountLineEditClassic.OnTextChanged += _ => HandleCustomAmountTextChanged(CustomAmountLineEditClassic, CustomAmountLineEdit, isModern: false);
        CustomAmountButton.Disabled = true;
        CustomAmountButton.ToggleMode = true;
        CustomAmountButton.OnPressed += _ =>
        {
            if (!IsCustomAmountValid(CustomAmountLineEdit.Text))
            {
                _customSelected = false;
                CustomAmountButton.Pressed = false;
                SaveCustomPerChemMaster();
                return;
            }
            _customAmount = FixedPoint2.New(int.Parse(CustomAmountLineEdit.Text));
            _customSelected = true;
            CustomAmountButton.Pressed = true;
            DeselectGrid();
            SaveCustomPerChemMaster();
            OnAmountSelected?.Invoke(_selectedAmount);
        };

        ApplyLayout();

        // Layout toggle in title bar, left of close button (same pattern as PopOutFancyWindow).
        if (CloseButton.Parent is { } header)
        {
            var layoutLabel = new Label
            {
                Text = _classicMode
                    ? Loc.GetString("chem-master-window-mode-classic")
                    : Loc.GetString("chem-master-window-mode-modern"),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 8, 0),
            };

            var layoutToggle = new SwitchButton
            {
                VerticalAlignment = VAlignment.Center,
                OffStateText = string.Empty,
                OnStateText = string.Empty,
                Pressed = _classicMode,
                ToolTip = Loc.GetString("chem-master-window-mode-tooltip"),
            };

            layoutToggle.OnPressed += args =>
            {
                _classicMode = layoutToggle.Pressed;
                layoutLabel.Text = _classicMode
                    ? Loc.GetString("chem-master-window-mode-classic")
                    : Loc.GetString("chem-master-window-mode-modern");
                ApplyLayout();
            };

            var layoutContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 6, 0),
                Children = { layoutLabel, layoutToggle },
            };

            header.AddChild(layoutContainer);
            layoutContainer.SetPositionInParent(header.ChildCount - 2);
        }
    }

    /// <summary>
    /// Builds the pill type selector for one layout.
    /// </summary>
    private static Button[] BuildPillTypeButtons(GridContainer grid, SpriteSystem sprite)
    {
        const int pillTypeCount = 20;
        var resourcePath = new ResPath(PillsRsiPath);
        var pillTypeGroup = new ButtonGroup();
        var buttons = new Button[pillTypeCount];

        for (uint i = 0; i < buttons.Length; i++)
        {
            var styleBase = StyleClass.ButtonOpenBoth;
            if (i == 9)
                styleBase = StyleClass.ButtonOpenLeft;
            else if (i == 10)
                styleBase = StyleClass.ButtonOpenRight;

            buttons[i] = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = pillTypeGroup,
            };

            var specifier = new SpriteSpecifier.Rsi(resourcePath, "pill" + (i + 1));
            var pillTypeTexture = new TextureRect
            {
                Texture = sprite.Frame0(specifier),
                TextureScale = new Vector2(1.75f, 1.75f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };

            buttons[i].AddChild(pillTypeTexture);
            grid.AddChild(buttons[i]);
        }

        return buttons;
    }

    /// <summary>
    /// Builds a 2x5 amount selection grid into the given GridContainer.
    /// Both modern tabs get their own grid instance but share the _selectedAmount state.
    /// </summary>
    private void BuildAmountGrid(GridContainer grid)
    {
        var amountGroup = new ButtonGroup();

        for (var idx = 0; idx < AmountConfigs.Length; idx++)
        {
            var (label, amount) = AmountConfigs[idx];
            var btn = new Button
            {
                Access = AccessLevel.Public,
                Text = label,
                ToggleMode = true,
                Group = amountGroup,
                MinSize = new Vector2(46, 0),
                Pressed = !_customSelected && amount == _selectedAmount,
                StyleClasses = { idx == 8 ? StyleClass.ButtonOpenRight : StyleClass.ButtonOpenBoth },
            };

            var capturedAmount = amount;
            btn.OnPressed += _ =>
            {
                _customSelected = false;
                CustomAmountButton.Pressed = false;
                SaveCustomPerChemMaster();
                OnAmountSelected?.Invoke(capturedAmount);
            };

            grid.AddChild(btn);
        }
    }

    private void DeselectGrid() { foreach (var c in AmountGrid.Children) if (c is Button b) b.Pressed = false; }

    private void SyncGrid(GridContainer grid)
    {
        if (_customSelected)
        {
            DeselectGrid();
            return;
        }

        var i = 0;
        foreach (var child in grid.Children)
        {
            if (child is Button btn && i < AmountConfigs.Length)
            {
                btn.Pressed = AmountConfigs[i].Amount == _selectedAmount;
                i++;
            }
        }
    }

    private void SaveCustomPerChemMaster() { if (_chemMasterNetEntity is {} id) _customPerChemMaster[id] = (CustomAmountLineEdit.Text, _customAmount, _customSelected); }

    private void HandleCustomAmountTextChanged(LineEdit source, LineEdit target, bool isModern)
    {
        if (target.Text != source.Text)
            target.Text = source.Text;
        if (isModern)
            CustomAmountButton.Disabled = !IsCustomAmountValid(source.Text);
        if (_customSelected)
        {
            if (IsCustomAmountValid(source.Text) && int.TryParse(source.Text, out var v))
                _customAmount = FixedPoint2.New(v);
            else
            {
                _customAmount = null;
                _customSelected = false;
                if (isModern)
                    CustomAmountButton.Pressed = false;
            }
        }
        SaveCustomPerChemMaster();
        UpdateClassicCustomButtons();
    }

    private void UpdateClassicCustomButtons()
    {
        var valid = IsCustomAmountValid(CustomAmountLineEditClassic.Text);
        void UpdateIn(Control root)
        {
            foreach (var child in root.Children)
            {
                if (child is ReagentButton rb && rb.Text == "#")
                    rb.Disabled = !valid;
                else if (child is Control c)
                    UpdateIn(c);
            }
        }
        UpdateIn(BufferInfoClassic);
        UpdateIn(InputContainerInfoClassic);
        UpdateIn(OutputContainerInfoClassic);
    }

    public void SetChemMasterEntity(NetEntity id)
    {
        _chemMasterNetEntity = id;
        if (!_customPerChemMaster.TryGetValue(id, out var s)) return;
        CustomAmountLineEdit.Text = s.Text;
        CustomAmountLineEditClassic.Text = s.Text;
        _customAmount = s.Amount;
        _customSelected = s.Selected;
        CustomAmountButton.Disabled = string.IsNullOrWhiteSpace(s.Text) || (CustomAmountLineEdit!.IsValid != null && !CustomAmountLineEdit!.IsValid(s.Text));
        CustomAmountButton.Pressed = _customSelected && !CustomAmountButton.Disabled;
        _customSelected = CustomAmountButton.Pressed;
        UpdateClassicCustomButtons();
        SyncGrid(AmountGrid);
    }

    /// <summary>
    /// Removes cached custom-amount state for the specified ChemMaster entity.
    /// </summary>
    /// <param name="id">The ChemMaster entity whose custom-amount state should be removed.</param>
    public static void ClearCustomForEntity(NetEntity id) => _customPerChemMaster.Remove(id);

    protected override void Dispose(bool disposing)
    {
        if (disposing && _chemMasterNetEntity is {} id)
            _customPerChemMaster.Remove(id);
        base.Dispose(disposing);
    }

    private void ApplyLayout()
    {
        ModernTabs.Visible = !_classicMode;
        ClassicTabs.Visible = _classicMode;

        var targetSize = _classicMode ? ClassicMinSize : _modernMinSize;
        MinSize = targetSize;
        // Force window to specified dimensions, MinSize alone doesn't shrink an already larger window
        SetSize = targetSize;
        if (!_classicMode)
        {
            CustomAmountButton.Disabled = !IsCustomAmountValid(CustomAmountLineEdit.Text);
        }
        else
        {
            UpdateClassicCustomButtons();
        }
    }

    private ReagentButton MakeReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
    {
        var reagentTransferButton = new ReagentButton(text, amount, id, isBuffer, styleClass);
        reagentTransferButton.OnPressed += args
            => OnReagentButtonPressed?.Invoke(args, reagentTransferButton);
        return reagentTransferButton;
    }

    /// <summary>
    /// Classic mode only: generates the full set of per-row amount buttons.
    /// Modern mode rows are buttons themselves - this is not called for them.
    /// </summary>
    private List<ReagentButton> CreateReagentTransferButtons(ReagentId reagent, bool isBuffer, bool addReagentButtons)
    {
        if (!addReagentButtons)
            return new List<ReagentButton>();

        // Classic: full button strip with # preceding 1 for custom amount
        var buttons = new List<ReagentButton>();

        var hashButton = new ReagentButton("#", ChemMasterReagentAmount.U1, reagent, isBuffer, StyleClass.ButtonOpenRight)
        {
            Disabled = !IsCustomAmountValid(CustomAmountLineEditClassic.Text)
        };
        hashButton.OnPressed += a => { if (IsCustomAmountValid(CustomAmountLineEditClassic.Text) && int.TryParse(CustomAmountLineEditClassic.Text, out var v)) OnCustomReagentButtonPressed?.Invoke(a, reagent, FixedPoint2.New(v), isBuffer); };
        buttons.Add(hashButton);

        var buttonConfigs = new (string text, ChemMasterReagentAmount amount, string styleClass)[]
        {
            ("1",   ChemMasterReagentAmount.U1,   StyleClass.ButtonOpenBoth),
            ("5",   ChemMasterReagentAmount.U5,   StyleClass.ButtonOpenBoth),
            ("10",  ChemMasterReagentAmount.U10,  StyleClass.ButtonOpenBoth),
            ("15",  ChemMasterReagentAmount.U15,  StyleClass.ButtonOpenBoth),
            ("20",  ChemMasterReagentAmount.U20,  StyleClass.ButtonOpenBoth),
            ("30",  ChemMasterReagentAmount.U30,  StyleClass.ButtonOpenBoth),
            ("40",  ChemMasterReagentAmount.U40,  StyleClass.ButtonOpenBoth),
            ("60",  ChemMasterReagentAmount.U60,  StyleClass.ButtonOpenBoth),
            ("120", ChemMasterReagentAmount.U120, StyleClass.ButtonOpenBoth),
            (Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All, StyleClass.ButtonOpenLeft),
        };

        foreach (var (text, amount, styleClass) in buttonConfigs)
        {
            buttons.Add(MakeReagentButton(text, amount, reagent, isBuffer, styleClass));
        }

        return buttons;
    }

    /// <summary>
    /// Update the UI state when new state data is received from the server.
    /// </summary>
    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (ChemMasterBoundUserInterfaceState)state;
        _lastState = castState;

        if (castState.UpdateLabel)
            LabelLine = GenerateLabel(castState);

        // when a different pill bottle / patch box is inserted,
        // allow its container label to be populated again.
        var currentContainer = castState.OutputContainerInfo?.Uid;
        if (currentContainer != _lastOutputContainer)
        {
            _lastOutputContainer = currentContainer;
            _containerLabelManuallySet = false;
            ContainerLabelLine = "";
        }

        // Until the user explicitly changes the container label, keep it
        // synchronized with either the existing container label or the
        // automatically generated item label.
        if (castState.OutputContainerInfo is not null &&
            !_containerLabelManuallySet)
        {
            var existingLabel = castState.OutputContainerInfo.ContainerLabel;

            ContainerLabelLine = !string.IsNullOrEmpty(existingLabel)
                ? existingLabel
                : LabelLine;
        }

        UpdatePanelInfo(castState);

        // Keep both layouts in sync with the server state.
        InputEjectButton.Disabled = castState.InputContainerInfo is null;
        InputEjectButtonClassic.Disabled = castState.InputContainerInfo is null;

        OutputEjectButton.Disabled = castState.OutputContainerInfo is null;
        OutputEjectButtonClassic.Disabled = castState.OutputContainerInfo is null;

        var output = castState.OutputContainerInfo;
        var bottleFull = output?.Reagents != null && output.CurrentVolume >= output.MaxVolume;
        var pillFull = output?.PillEntities != null && output.CurrentVolume >= output.MaxVolume;
        var patchFull = output?.PatchEntities != null && output.CurrentVolume >= output.MaxVolume;

        CreateBottleButton.Disabled = castState.OutputContainerInfo?.Reagents == null || bottleFull;
        CreateBottleButtonClassic.Disabled = castState.OutputContainerInfo?.Reagents == null || bottleFull;
        CreateBottleButton.ToolTip = !CreateBottleButton.Disabled ? null : bottleFull ? Loc.GetString("chem-master-window-create-bottle-full-tooltip") : Loc.GetString("chem-master-window-create-bottle-tooltip");
        CreateBottleButtonClassic.ToolTip = !CreateBottleButtonClassic.Disabled ? null : bottleFull ? Loc.GetString("chem-master-window-create-bottle-full-tooltip") : Loc.GetString("chem-master-window-create-bottle-tooltip");

        CreatePillButton.Disabled = castState.OutputContainerInfo?.PillEntities == null || pillFull;
        CreatePillButtonClassic.Disabled = castState.OutputContainerInfo?.PillEntities == null || pillFull;
        CreatePillButton.ToolTip = !CreatePillButton.Disabled ? null : pillFull ? Loc.GetString("chem-master-window-create-pill-full-tooltip") : Loc.GetString("chem-master-window-create-pill-tooltip");
        CreatePillButtonClassic.ToolTip = !CreatePillButtonClassic.Disabled ? null : pillFull ? Loc.GetString("chem-master-window-create-pill-full-tooltip") : Loc.GetString("chem-master-window-create-pill-tooltip");

        CreatePatchButton.Disabled = castState.OutputContainerInfo?.PatchEntities == null || patchFull;
        CreatePatchButtonClassic.Disabled = castState.OutputContainerInfo?.PatchEntities == null || patchFull;
        CreatePatchButton.ToolTip = !CreatePatchButton.Disabled ? null : patchFull ? Loc.GetString("chem-master-window-create-patch-full-tooltip") : Loc.GetString("chem-master-window-create-patch-tooltip");
        CreatePatchButtonClassic.ToolTip = !CreatePatchButtonClassic.Disabled ? null : patchFull ? Loc.GetString("chem-master-window-create-patch-full-tooltip") : Loc.GetString("chem-master-window-create-patch-tooltip");

        var valveText = Loc.GetString(castState.ValveOpen
            ? "chem-master-window-valve-open"
            : "chem-master-window-valve-closed");

        ValveButton.Text = valveText;
        ValveButtonClassic.Text = valveText;

        UpdateDosageFields(castState);
    }

    private void UpdateDosageFields(ChemMasterBoundUserInterfaceState castState)
    {
        var output = castState.OutputContainerInfo;
        var remainingCapacity = output is null ? 0 : (output.MaxVolume - output.CurrentVolume).Int();
        var holdsReagents = output?.Reagents != null;
        var itemNumberMax = holdsReagents ? 0 : remainingCapacity;
        var bottleAmountMax = holdsReagents ? remainingCapacity : 0;
        var outputVolume = castState.DrawSource switch
        {
            ChemMasterDrawSource.Internal => castState.BufferCurrentVolume?.Int() ?? 0,
            ChemMasterDrawSource.External => castState.InputContainerInfo?.CurrentVolume.Int() ?? 0,
            _ => 0,
        };

        // Modern layout.
        PillDosage.Value = (int) Math.Min(outputVolume, castState.PillDosageLimit);
        PatchDosage.Value = (int) Math.Min(outputVolume, castState.PatchDosageLimit);
        PillTypeButtons[castState.SelectedPillType].Pressed = true;
        PillTypeButtonsClassic[castState.SelectedPillType].Pressed = true;

        PillNumber.IsValid = x => x >= 0 && x <= itemNumberMax;
        PillDosage.IsValid = x => x > 0 && x <= castState.PillDosageLimit;
        PatchNumber.IsValid = x => x >= 0 && x <= itemNumberMax;
        PatchDosage.IsValid = x => x > 0 && x <= castState.PatchDosageLimit;
        BottleDosage.IsValid = x => x >= 0 && x <= bottleAmountMax;

        PillNumber.Value = PillDosage.Value > 0
            ? Math.Min(outputVolume / PillDosage.Value, itemNumberMax)
            : 0;
        PatchNumber.Value = PatchDosage.Value > 0
            ? Math.Min(outputVolume / PatchDosage.Value, itemNumberMax)
            : 0;
        BottleDosage.Value = Math.Min(bottleAmountMax, outputVolume);

        // Classic layout.
        PillDosageClassic.Value = (int) Math.Min(outputVolume, castState.PillDosageLimit);
        PatchDosageClassic.Value = (int) Math.Min(outputVolume, castState.PatchDosageLimit);

        PillNumberClassic.IsValid = x => x >= 0 && x <= itemNumberMax;
        PillDosageClassic.IsValid = x => x > 0 && x <= castState.PillDosageLimit;
        PatchNumberClassic.IsValid = x => x >= 0 && x <= itemNumberMax;
        PatchDosageClassic.IsValid = x => x > 0 && x <= castState.PatchDosageLimit;
        BottleDosageClassic.IsValid = x => x >= 0 && x <= bottleAmountMax;

        PillNumberClassic.Value = PillDosageClassic.Value > 0
            ? Math.Min(outputVolume / PillDosageClassic.Value, itemNumberMax)
            : 0;
        PatchNumberClassic.Value = PatchDosageClassic.Value > 0
            ? Math.Min(outputVolume / PatchDosageClassic.Value, itemNumberMax)
            : 0;
        BottleDosageClassic.Value = Math.Min(bottleAmountMax, outputVolume);
    }

    private string GenerateLabel(ChemMasterBoundUserInterfaceState state)
    {
        var reagents = state.DrawSource switch
        {
            ChemMasterDrawSource.Internal => state.BufferReagents,
            ChemMasterDrawSource.External => state.InputContainerInfo?.Reagents ?? [],
            _ => throw new($"Chemmaster {state.OutputContainerInfo} draw source is not set"),
        };

        if (!reagents.Any())
            return "";

        var reagent = reagents.MinBy(r => r.Quantity).Reagent;
        _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
        return proto?.LocalizedName ?? "";
    }

    private void UpdatePanelInfo(ChemMasterBoundUserInterfaceState state)
    {
        BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
        BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;

        // Modern layout containers
        BuildContainerUI(InputContainerInfo, state.InputContainerInfo, true, modernMode: true);
        BuildContainerUI(OutputContainerInfo, state.OutputContainerInfo, false, modernMode: true, "chem-master-window-no-output-container-loaded-text");
        BuildOutputLeftContainer(OutputInputContainerInfo, state, modernMode: false);

        // Classic layout containers
        BuildContainerUI(InputContainerInfoClassic, state.InputContainerInfo, true, modernMode: false);
        BuildContainerUI(OutputContainerInfoClassic, state.OutputContainerInfo, false, modernMode: false, "chem-master-window-no-output-container-loaded-text");
        BuildOutputLeftContainer(OutputInputContainerInfoClassic, state, modernMode: false);

        BufferInfo.Children.Clear();
        BufferInfoClassic.Children.Clear();

        var sortLabel = state.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => Loc.GetString("chem-master-window-sort-type-alphabetical"),
            ChemMasterSortingType.Quantity => Loc.GetString("chem-master-window-sort-type-quantity"),
            ChemMasterSortingType.Latest => Loc.GetString("chem-master-window-sort-type-latest"),
            _ => Loc.GetString("chem-master-window-sort-type-none")
        };
        BufferSortButton.Text = sortLabel;
        BufferSortButtonClassic.Text = sortLabel;

        OutputBufferDraw.Pressed = state.DrawSource == ChemMasterDrawSource.Internal;
        OutputBeakerDraw.Pressed = state.DrawSource == ChemMasterDrawSource.External;
        OutputBufferDrawClassic.Pressed = state.DrawSource == ChemMasterDrawSource.Internal;
        OutputBeakerDrawClassic.Pressed = state.DrawSource == ChemMasterDrawSource.External;

        if (!state.BufferReagents.Any())
        {
            var emptyLabel = new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") };
            var emptyLabelClassic = new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") };
            BufferInfo.Children.Add(emptyLabel);
            BufferInfoClassic.Children.Add(emptyLabelClassic);
            return;
        }

        // Buffer volume header row
        void AddBufferHeader(BoxContainer target)
        {
            var hbox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            hbox.AddChild(new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " });
            hbox.AddChild(new Label
            {
                Text = $"{state.BufferCurrentVolume}u",
                StyleClasses = { StyleClass.LabelWeak }
            });
            target.AddChild(hbox);
        }
        AddBufferHeader(BufferInfo);
        AddBufferHeader(BufferInfoClassic);

        var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
        foreach (var (reagent, quantity) in state.BufferReagents)
        {
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
            var reagentColor = proto?.SubstanceColor ?? default(Color);
            reagentList.Add((reagent, name, reagentColor, quantity));
        }

        reagentList = state.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => reagentList.OrderBy(x => x.name).ToList(),
            ChemMasterSortingType.Quantity => reagentList.OrderByDescending(x => x.quantity).ToList(),
            ChemMasterSortingType.Latest => Enumerable.Reverse(reagentList).ToList(),
            _ => reagentList
        };

        var rowCount = 0;
        foreach (var reagent in reagentList)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: true));
            BufferInfoClassic.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: false));
            rowCount++;
        }

        // A bit messy, but it fixes the search resetting on click.
        if (!string.IsNullOrEmpty(SearchBar.Text))
            UpdateReagentPrototypes(SearchBar.Text);
    }

    private void BuildOutputLeftContainer(Control control, ChemMasterBoundUserInterfaceState state, bool modernMode)
    {
        if (state.DrawSource == ChemMasterDrawSource.Internal)
        {
            // Show buffer contents when packaging from buffer
            control.Children.Clear();
            if (!state.BufferReagents.Any())
            {
                control.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
                return;
            }
            control.Children.Add(new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " },
                    new Label { Text = $"{state.BufferCurrentVolume}u", StyleClasses = { StyleClass.LabelWeak } }
                }
            });
            var rowCount = 0;
            foreach (var (reagent, quantity) in state.BufferReagents)
            {
                _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                control.Children.Add(BuildReagentRow(default, rowCount++, name, reagent, quantity, true, false, modernMode));
            }
            return;
        }
        BuildContainerUI(control, state.InputContainerInfo, false, modernMode, "chem-master-window-no-input-container-loaded-text");
    }

    private void BuildContainerUI(Control control, ContainerInfo? info, bool addReagentButtons, bool modernMode, string emptyLoc = "chem-master-window-no-container-loaded-text")
    {
        control.Children.Clear();

        if (info is null)
        {
            control.Children.Add(new Label { Text = Loc.GetString(emptyLoc) });
            return;
        }

        control.Children.Add(new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = $"{info.DisplayName}: " },
                new Label
                {
                    Text = $"{info.CurrentVolume}/{info.MaxVolume}",
                    StyleClasses = { StyleClass.LabelWeak }
                }
            }
        });

        var rowCount = 0;

        if (info.PillEntities != null)
        {
            foreach (var (id, quantity) in info.PillEntities)
            {
                control.Children.Add(BuildReagentRow(
                    default,
                    rowCount++,
                    id,
                    default,
                    quantity,
                    false,
                    addReagentButtons,
                    modernMode));
            }
        }

        if (info.PatchEntities != null)
        {
            foreach (var (id, quantity) in info.PatchEntities)
            {
                control.Children.Add(BuildReagentRow(
                    default,
                    rowCount++,
                    id,
                    default,
                    quantity,
                    false,
                    addReagentButtons,
                    modernMode));
            }
        }

        if (info.Reagents != null)
        {
            foreach (var reagent in info.Reagents)
            {
                _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                var reagentColor = proto?.SubstanceColor ?? default(Color);
                control.Children.Add(BuildReagentRow(reagentColor, rowCount++, name, reagent.Reagent, reagent.Quantity, false, addReagentButtons, modernMode));
            }
        }
    }

    private Control BuildReagentRow(Color reagentColor, int rowCount, string name, ReagentId reagent, FixedPoint2 quantity, bool isBuffer, bool addReagentButtons, bool modernMode)
    {
        var rowColor1 = Color.FromHex("#1B1B1E");
        var rowColor2 = Color.FromHex("#202025");
        var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;
        var hasColor = reagentColor != default(Color) && addReagentButtons;

        if (modernMode && addReagentButtons)
        {
            // Modern: the entire row is a ReagentButton. Amount is read from the selected amount at click time. If custom amount is selected, send via custom message; otherwise use _selectedAmount.
            var rowBtn = new ReagentButton(string.Empty, _selectedAmount, reagent, isBuffer, StyleClass.ButtonSquare)
            {
                HorizontalExpand = true,
            };
            rowBtn.OnPressed += a => { if (_customSelected && _customAmount is {} c) OnCustomReagentButtonPressed?.Invoke(a, reagent, c, isBuffer); else { rowBtn.Amount = _selectedAmount; OnReagentButtonPressed?.Invoke(a, rowBtn); } };

            // Color row at the start of the button
            var row = new PanelContainer
            {
                MinSize = new Vector2(4, 30),
                Margin = new Thickness(-4, 0, 6, 0),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = hasColor ? reagentColor : Color.Transparent,
                }
            };

            var inner = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    row,
                    new Label { Text = $"{name}: " },
                    new Label
                    {
                        Text = $"{quantity}u",
                        StyleClasses = { StyleClass.LabelWeak }
                    },
                    new Control { HorizontalExpand = true },
                }
            };
            rowBtn.AddChild(inner);
            return rowBtn;
        }

        // Classic: striped PanelContainer with full per-row amount buttons
        if (reagentColor == default || !addReagentButtons)
            reagentColor = currentRowColor;

        var reagentButtonConstructors = CreateReagentTransferButtons(reagent, isBuffer, addReagentButtons);

        var rowContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new PanelContainer
                {
                    Name = "colorPanel",
                    VerticalExpand = true,
                    MinWidth = 4,
                    PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
                    Margin = new Thickness(0, 1, 4, 1)
                },
                new Label { Text = $"{name}: " },
                new Label
                {
                    Text = $"{quantity}u",
                    StyleClasses = { StyleClass.LabelWeak }
                },
                new Control { HorizontalExpand = true },
            }
        };

        foreach (var btn in reagentButtonConstructors)
        {
            rowContainer.AddChild(btn);
        }

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(currentRowColor),
            Children = { rowContainer }
        };
    }

    public string LabelLine
    {
        get => _classicMode
            ? LabelLineEditClassic.Text
            : LabelLineEdit.Text;

        private set
        {
            LabelLineEdit.Text = value;
            LabelLineEditClassic.Text = value;
        }
    }

    // separate label for the pill bottle / patch box itself.
    public string ContainerLabelLine
    {
        get => _classicMode
            ? ContainerLabelLineEditClassic.Text
            : ContainerLabelLineEdit.Text;

        private set
        {
            _settingContainerLabelProgrammatically = true;

            ContainerLabelLineEdit.Text = value;
            ContainerLabelLineEditClassic.Text = value;

            _settingContainerLabelProgrammatically = false;
        }
    }

    private void UpdateReagentPrototypes(string? filter = null)
    {
        if (_lastState == null)
            return;

        BufferInfo.Children.Clear();
        BufferInfoClassic.Children.Clear();

        if (!_lastState.BufferReagents.Any())
        {
            BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
            BufferInfoClassic.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
            return;
        }

        // Re-add header (mirrors UpdatePanelInfo) so search doesn't hide buffer volume
        void AddHeader(BoxContainer target)
        {
            var h = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            h.AddChild(new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " });
            h.AddChild(new Label { Text = $"{_lastState.BufferCurrentVolume}u", StyleClasses = { StyleClass.LabelWeak } });
            target.AddChild(h);
        }
        AddHeader(BufferInfo);
        AddHeader(BufferInfoClassic);

        var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
        foreach (var (reagent, quantity) in _lastState.BufferReagents)
        {
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
            var reagentColor = proto?.SubstanceColor ?? default(Color);
            reagentList.Add((reagent, name, reagentColor, quantity));
        }

        if (!string.IsNullOrEmpty(filter))
        {
            var trimmedFilter = filter.Trim();

            reagentList = reagentList
                .Where(r =>
                    r.name.Contains(
                        trimmedFilter,
                        StringComparison.InvariantCultureIgnoreCase)
                    || r.reagentId.Prototype.ToString().Contains(
                        trimmedFilter,
                        StringComparison.InvariantCultureIgnoreCase))
                .ToList();
        }

        reagentList = _lastState.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => reagentList.OrderBy(x => x.name).ToList(),
            ChemMasterSortingType.Quantity => reagentList.OrderByDescending(x => x.quantity).ToList(),
            ChemMasterSortingType.Latest => Enumerable.Reverse(reagentList).ToList(),
            _ => reagentList
        };

        var rowCount = 0;
        foreach (var reagent in reagentList)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: true));
            BufferInfoClassic.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: false));
            rowCount++;
        }
    }

    public event Action<ChemMasterReagentAmount>? OnAmountSelected;

    public void SetSelectedAmount(ChemMasterReagentAmount amount)
    {
        _selectedAmount = amount;
        if (!_customSelected)
            CustomAmountButton.Pressed = false;
        SyncGrid(AmountGrid);
    }
}

public sealed class ReagentButton : Button
{
    public ChemMasterReagentAmount Amount { get; set; }
    public readonly bool IsBuffer;
    public ReagentId Id { get; }
    public ReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
    {
        AddStyleClass(styleClass);
        Text = text;
        Amount = amount;
        Id = id;
        IsBuffer = isBuffer;
    }
}
