using System.Numerics;
using Content.Shared._Starlight.Power.BluespaceHarvester;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Power.UI;

[GenerateTypedNameReferences]
public sealed partial class BluespaceHarvesterWindow : DefaultWindow
{
    public event Action<int>? OnDesiredLevelChanged;
    public event Action<string>? OnPoolRequested;

    private readonly Dictionary<string, (PanelContainer panel, Label name, Button button, Label cost)> _poolRows = new();

    // Flag to suppress OnValueChanged when changing slider value 
    private bool _suppressSlider;
    private int _predictedDesiredLevel = -1;

    // Background colors 4 zebra effect
    private const string PoolRowBackgroundEvenHex = "#252545";
    private const string PoolRowBackgroundOddHex = "#1a1a35";

    public BluespaceHarvesterWindow()
    {
        RobustXamlLoader.Load(this);

        DesiredMinButton.OnPressed += _ => SetDesiredLevelWithPrediction(0);
        DesiredDecrementButton.OnPressed += _ => SetDesiredLevelWithPrediction(_predictedDesiredLevel >= 0
            ? _predictedDesiredLevel - 1
            : (int) MathF.Round(DesiredLevelSlider.Value) - 1);
        DesiredIncrementButton.OnPressed += _ => SetDesiredLevelWithPrediction(_predictedDesiredLevel >= 0
            ? _predictedDesiredLevel + 1
            : (int) MathF.Round(DesiredLevelSlider.Value) + 1);
        DesiredMaxButton.OnPressed += _ => SetDesiredLevelWithPrediction((int) MathF.Round(DesiredLevelSlider.MaxValue));

        DesiredLevelSlider.OnValueChanged += args =>
        {
            if (_suppressSlider)
                return;

            SetDesiredLevelWithPrediction((int) MathF.Round(args.Value));
        };
    }

    private void SetDesiredLevelWithPrediction(int level)
    {
        var min = (int) MathF.Round(DesiredLevelSlider.MinValue);
        var max = (int) MathF.Round(DesiredLevelSlider.MaxValue);
        var clamped = Math.Clamp(level, min, max);

        _predictedDesiredLevel = clamped;

        // Update Slider value without triggering OnValueChanged    
        _suppressSlider = true;
        DesiredLevelSlider.Value = clamped;
        _suppressSlider = false;

        DesiredLevelValue.Text = clamped.ToString();

        OnDesiredLevelChanged?.Invoke(clamped);
    }

    public void UpdateState(BluespaceHarvesterUiState state)
    {
        InputLevelValue.Text = state.CurrentLevel.ToString();

        // Server confirmed our prediction clear it
        if (_predictedDesiredLevel >= 0 && _predictedDesiredLevel == state.DesiredLevel)
            _predictedDesiredLevel = -1;

        // Updates slider only if theres no active prediction
        if (_predictedDesiredLevel < 0)
        {
            DesiredLevelValue.Text = state.DesiredLevel.ToString();

            _suppressSlider = true;
            DesiredLevelSlider.MinValue = 0;
            DesiredLevelSlider.MaxValue = state.MaxLevel;
            DesiredLevelSlider.Value = state.DesiredLevel;
            _suppressSlider = false;
        }
        else
        {
            _suppressSlider = true;
            DesiredLevelSlider.MinValue = 0;
            DesiredLevelSlider.MaxValue = state.MaxLevel;
            _suppressSlider = false;
        }

        CurrentPowerValue.Text = FormatPower(state.CurrentPower);
        NextLevelPowerValue.Text = FormatPower(state.PowerForNextLevel);
        NetworkSupplyValue.Text = FormatPower(state.NetworkSupply);

        // Show danger warning when in "dangerous" mode (level >= 7)
        DangerWarningPanel.Visible = state.DangerousMode && !state.IsBlocked;
        BlockedWarningPanel.Visible = state.IsBlocked;

        AvailablePointsValue.Text = state.AvailablePoints.ToString();
        TotalPointsValue.Text = state.TotalPoints.ToString();

        UpdatePools(state);
    }

    /// <summary>
    /// Updates the list of available pools in the UI
    /// </summary>
    private void UpdatePools(BluespaceHarvesterUiState state)
    {
        var existingIds = new HashSet<string>(_poolRows.Keys);
        var newIds = new HashSet<string>();

        foreach (var pool in state.Pools)
            newIds.Add(pool.Id);

        // Delete pools that are no longer present
        foreach (var id in existingIds)
        {
            if (!newIds.Contains(id))
            {
                PoolsContainer.RemoveChild(_poolRows[id].panel);
                _poolRows.Remove(id);
            }
        }

        var index = 0; // just funny "Zebra" background effect 
        foreach (var pool in state.Pools)
        {
            var canAfford = state.AvailablePoints >= pool.Cost;

            if (_poolRows.TryGetValue(pool.Id, out var existing))
            {
                existing.button.Disabled = !canAfford;
                existing.button.Modulate = canAfford ? Color.FromHex("#90EE90") : Color.White;
                existing.cost.Text = $"{pool.Cost} pts";
                existing.name.Text = Loc.GetString(pool.NameKey);

                if (existing.panel.PanelOverride is StyleBoxFlat styleBox)
                {
                    styleBox.BackgroundColor = Color.FromHex(index % 2 == 0 ? PoolRowBackgroundEvenHex : PoolRowBackgroundOddHex);
                }
            }
            else
            {
                var rowPanel = new PanelContainer
                {
                    HorizontalExpand = true,
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex(index % 2 == 0 ? PoolRowBackgroundEvenHex : PoolRowBackgroundOddHex),
                        ContentMarginLeftOverride = 6,
                        ContentMarginRightOverride = 6,
                        ContentMarginTopOverride = 4,
                        ContentMarginBottomOverride = 4
                    }
                };

                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 8,
                    HorizontalExpand = true
                };

                var name = new Label
                {
                    Text = Loc.GetString(pool.NameKey),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center
                };

                var cost = new Label
                {
                    Text = $"{pool.Cost} pts",
                    MinSize = new Vector2(70, 0),
                    Modulate = Color.FromHex("#FFD700"),
                    VerticalAlignment = VAlignment.Center
                };

                var button = new Button
                {
                    Text = Loc.GetString("bluespace-harvester-buy"),
                    Disabled = !canAfford,
                    MinWidth = 60
                };

                if (canAfford)
                    button.Modulate = Color.FromHex("#90EE90");

                var poolId = pool.Id;
                button.OnPressed += _ => OnPoolRequested?.Invoke(poolId);

                row.AddChild(name);
                row.AddChild(cost);
                row.AddChild(button);

                rowPanel.AddChild(row);
                PoolsContainer.AddChild(rowPanel);
                _poolRows[pool.Id] = (rowPanel, name, button, cost);
            }

            index++;
        }
    }

    private static string FormatPower(float value)
    {
        var abs = MathF.Abs(value);
        if (abs >= 1_000_000f)
            return $"{value / 1_000_000f:0.##} MW";
        if (abs >= 1_000f)
            return $"{value / 1_000f:0.##} kW";
        return $"{value:0.##} W";
    }
}
