using System.Linq;
using System.Numerics;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reagent; // Starlight
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared._Starlight.Medical;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;

    // Starlight-start: Printable health reports.
    public event Action? PrintReportPressed;

    public void SetPrintReportVisible(bool visible)
    {
        PrintReportButton.Visible = visible;
    }
    // Starlight-end

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();

        PrintReportButton.OnPressed += _ => PrintReportPressed?.Invoke(); // Starlight-edit: Printable health reports.
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        PrintReportButton.Disabled = true; // Starlight-edit: Printable health reports.

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            NoPatientDataText.Visible = true;
            // Starlight begin - hide chemicals section on invalid target
            ChemicalsDivider.Visible = false;
            ChemicalsContainer.Visible = false;
            // Starlight end
            return;
        }

        NoPatientDataText.Visible = false;
        PrintReportButton.Disabled = !PrintReportButton.Visible || !(state.ScanMode ?? false) || !(state.CanPrint ?? false); // Starlight-edit: Printable health reports.
        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidAppearanceComponent>(target.Value,
                out var humanoidAppearanceComponent)
                ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoidAppearanceComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic
        // Starlight-start: shared formatting.
        TemperatureLabel.Text = HealthAnalyzerFormatting.FormatTemperature(state.Temperature);
        BloodLabel.Text = HealthAnalyzerFormatting.FormatBloodLevelWithSeverity(state.BloodLevel);
        BloodLabel.FontColorOverride = HealthAnalyzerFormatting.GetBloodLevelSeverityColor(state.BloodLevel);
        // Starlight-end

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent)
                ? HealthAnalyzerFormatting.GetStatusText(mobStateComponent.CurrentState) //Starkight-edit: shared formattng
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // Total Damage

        DamageLabel.Text = damageable.TotalDamage.ToString();

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        // Damage Groups
        /* Starlight begin - old damage group sorting by highest damage
        var damageSortedGroups =
            damageable.DamagePerGroup.OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);
         Starlight end */
        var damagePerType = damageable.Damage.DamageDict;
        //Starlight begin - Sort damage groups in a fixed order and add metabolizing section
        var sortedGroups = damageable.DamagePerGroup
            .OrderBy(g => HealthAnalyzerFormatting.GetDamageGroupSortKey(g.Key))
            .ThenBy(g => g.Key)
            .ToDictionary(g => g.Key, g => g.Value);

        DrawChemicals(state.Chemicals);
        // Starlight end
        DrawDiagnosticGroups(sortedGroups, damagePerType);
    }
    // Starlight-start: Draw Damage Groups in a two column grid in their own boxes.
    private void DrawDiagnosticGroups(
        Dictionary<string, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        var gridContainer = new GridContainer
        {
            Columns = 2,
        };

        GroupsContainer.AddChild(gridContainer);

        var columnIndex = 0;
        foreach (var (damageGroupId, damageAmount) in groups)
        {
            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            // Create a bordered box for each damage group
            var groupBox = new PanelContainer
            {
                Margin = new Thickness(2),
                MinWidth = 155,
            };

            // Boxes in the second column get right aligned
            if (columnIndex % 2 == 1)
            {
                groupBox.HorizontalAlignment = HAlignment.Right;
            }

            groupBox.PanelOverride = new StyleBoxFlat
            {
                BorderColor = Color.Gray,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };

            var groupContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Begin,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            var titleRow = CreateDiagnosticGroupTitleRow(groupTitleText, (float)damageAmount, damageGroupId);
            groupContainer.AddChild(titleRow);

            // Add divider line under the title row
            var divider = new PanelContainer
            {
                MinHeight = 1,
                Margin = new Thickness(0, 0, 0, 4),
            };
            divider.PanelOverride = new StyleBoxFlat(Color.Gray);
            groupContainer.AddChild(divider);

            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageTypeName = _prototypes.Index<DamageTypePrototype>(type).LocalizedName;
                var typeId = type.ToString().ToLowerInvariant();

                var damageRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(0, 2),
                };

                // Add damage type icon
                damageRow.AddChild(new TextureRect
                {
                    SetSize = new Vector2(15, 15),
                    Texture = GetTexture(typeId),
                    Margin = new Thickness(0, 0, 4, 0),
                });

                var typeLabel = new Label
                {
                    Text = damageTypeName,
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Left,
                };

                var amountLabel = new Label
                {
                    Text = typeAmount.ToString(),
                    HorizontalAlignment = HAlignment.Right,
                };

                damageRow.AddChild(typeLabel);
                damageRow.AddChild(amountLabel);
                groupContainer.AddChild(damageRow);
            }

            groupBox.AddChild(groupContainer);
            gridContainer.AddChild(groupBox);
            columnIndex++;
        }
    }

    #region Starlight begin
    private void DrawChemicals(List<(string ReagentId, FixedPoint2 Quantity, FixedPoint2 StomachQuantity)>? chemicals)
    {
        ChemicalsContainer.RemoveAllChildren();

        var hasChemicals = chemicals != null && chemicals.Count > 0;

        if (!hasChemicals || chemicals == null)
        {
            ChemicalsDivider.Visible = false;
            ChemicalsContainer.Visible = false;
            return;
        }

        ChemicalsDivider.Visible = true;
        ChemicalsContainer.Visible = true;

        var sortedReagents = chemicals.OrderByDescending(r => r.Quantity + r.StomachQuantity).ToList();

        foreach (var reagent in sortedReagents)
        {
            var reagentName = Loc.GetString("health-analyzer-window-entity-unknown-text");
            var reagentColor = Color.White;

            if (_prototypes.TryIndex<ReagentPrototype>(reagent.ReagentId, out var reagentProto))
            {
                reagentName = reagentProto.LocalizedName;
                reagentColor = reagentProto.SubstanceColor;
            }

            var rowContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 2),
            };

            // Color bar
            var colorBar = new PanelContainer
            {
                MinWidth = 10,
                MinHeight = 16,
                Margin = new Thickness(0, 0, 6, 0),
            };
            colorBar.PanelOverride = new StyleBoxFlat(reagentColor);

            var nameLabel = new Label
            {
                Text = reagentName,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
            };

            var quantityLabel = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Right,
            };

            var msg = new FormattedMessage();
            if (reagent.StomachQuantity > FixedPoint2.Zero && reagent.Quantity > FixedPoint2.Zero)
            {
                var formatted = Loc.GetString("health-analyzer-window-quantity-both", ("stomach", reagent.StomachQuantity), ("blood", reagent.Quantity));
                msg.AddMessage(FormattedMessage.FromMarkupOrThrow(formatted));
            }
            else if (reagent.StomachQuantity > FixedPoint2.Zero)
            {
                var formatted = Loc.GetString("health-analyzer-window-quantity-stomach", ("stomach", reagent.StomachQuantity));
                msg.AddMessage(FormattedMessage.FromMarkupOrThrow(formatted));
            }
            else if (reagent.Quantity > FixedPoint2.Zero)
            {
                var formatted = Loc.GetString("health-analyzer-window-quantity-blood", ("blood", reagent.Quantity));
                msg.AddMessage(FormattedMessage.FromMarkupOrThrow(formatted));
            }
            quantityLabel.SetMessage(msg);

            rowContainer.AddChild(colorBar);
            rowContainer.AddChild(nameLabel);
            rowContainer.AddChild(quantityLabel);
            ChemicalsContainer.AddChild(rowContainer);
        }
    }
    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/_Starlight/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private BoxContainer CreateDiagnosticGroupTitleRow(string text, float damageAmount, string damageGroupId)
    {
        var titleColor = HealthAnalyzerFormatting.GetDamageSeverityColor(damageAmount);
        var exclamations = HealthAnalyzerFormatting.GetDamageSeveritySuffix(damageAmount);
        var titleRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 4),
        };

        var groupId = damageGroupId.ToLowerInvariant();

        // Add damage group icon
        titleRow.AddChild(new TextureRect
        {
            SetSize = new Vector2(15, 15),
            Texture = GetTexture(groupId),
            Margin = new Thickness(0, 0, 4, 0),
            VerticalAlignment = VAlignment.Center,
        });

        var titleLabel = new Label
        {
            Text = string.IsNullOrEmpty(exclamations) ? text : $"{text} {exclamations}",
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = titleColor,
        };

        titleRow.AddChild(titleLabel);

        return titleRow;
    }
    #endregion
}
