- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 6h # Starlight
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 6h # Starlight
    - !type:DepartmentTimeRequirement
      department: Security
      time: 6h # Starlight
# Starlight start
    - !type:DepartmentTimeRequirement
      department: Science
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6h
# Starlight end
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10h # Starlight
# Starlight start
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:RoleTimeRequirement
      role: JobStationAi
      time: 1h
    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h
    - !type:OverallPlaytimeRequirement
      time: 7h
    HeadOfSecurity:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 8h
    ChiefEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 3h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 1h
    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobScientist
      time: 1h
    ChiefMedicalOfficer:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 1h
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 1h
    Quartermaster:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 1h
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 2h
    MedicalDoctor:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobMedicalIntern
      time: 1h
    Chemist:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobMedicalIntern
      time: 1h
    Paramedic:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 1h
    Coroner:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobMedicalIntern
      time: 1h
    StationEngineer:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobTechnicalAssistant
      time: 1h
    AtmosphericTechnician:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 1h
    Warden:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 20h
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 1h
    SecurityCadet:
    - !type:OverallPlaytimeRequirement
      time: 30h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 15h
      inverted: true # stop playing intern if you're good at security!
    SecurityOfficer:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
    Detective:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10h
    Brigmedic:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 8h
    StationAi:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobBorg
      time: 3h
    Borg:
    - !type:OverallPlaytimeRequirement
      time: 1h
    Bartender:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobServiceWorker
      time: 20m
    Chef:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobServiceWorker
      time: 20m
    Scientist:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobResearchAssistant
      time: 1h
    SalvageSpecialist:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 90m
    Botanist:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobServiceWorker
      time: 20m
    Clown:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobPassenger
      time: 10m
    CargoTechnician:
    - !type:OverallPlaytimeRequirement
      time: 0
    TechnicalAssistant:
    - !type:OverallPlaytimeRequirement
      time: 5m
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 15h
      inverted: true
    MedicalIntern:
    - !type:OverallPlaytimeRequirement
      time: 5m
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 15h
      inverted: true 
    ResearchAssistant:
    - !type:OverallPlaytimeRequirement
      time: 5m
    - !type:DepartmentTimeRequirement
      department: Science
      time: 15h
      inverted: true 
    Chaplain:
    - !type:OverallPlaytimeRequirement
      time: 0
    Janitor:
    - !type:OverallPlaytimeRequirement
      time: 0
    Lawyer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Librarian:
    - !type:OverallPlaytimeRequirement
      time: 0
    Mime:
    - !type:OverallPlaytimeRequirement
      time: 0
    Musician:
    - !type:OverallPlaytimeRequirement
      time: 0
    ServiceWorker:
    - !type:OverallPlaytimeRequirement
      time: 5m
    Visitor:
    - !type:OverallPlaytimeRequirement
      time: 0
# Starlight end