using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.UI.Kitchen
{
    /// <summary>
    /// IcecreammakerMenu is a modified version of MicrowaveMenu.xaml.cs to remove extra buttons and only have a start, stop, and eject.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class IceCreamMakerMenu : FancyWindow
    {
        [Dependency] private IGameTiming _timing = default!;

        public event Action<BaseButton.ButtonEventArgs, int>? OnCookTimeSelected;

        public ButtonGroup CookTimeButtonGroup { get; }

        public bool IsBusy;
        public bool IsSafe;
        public TimeSpan CurrentCooktimeEnd;
        public TimeSpan StartedCooktime = TimeSpan.FromSeconds(10);

        public IceCreamMakerMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            CookTimeButtonGroup = new ButtonGroup();

            CurrentCookTimeInfoLabel.Text = Loc.GetString("microwave-bound-user-interface-current-cook-time-label", ("time", StartedCooktime.ToString(@"mm\:ss"))); // Starlight-edit
        }

        public void ToggleBusyDisableOverlayPanel(bool shouldDisable)
        {
            DisableCookingPanelOverlay.Visible = shouldDisable;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!IsBusy)
                return;

            CurrentCookTimeInfoLabel.Text = Loc.GetString("microwave-bound-user-interface-current-cook-time-label", ("time", (_timing.CurTime - StartedCooktime).ToString(@"mm\:ss"))); // Starlight-edit
        }

        public sealed class MicrowaveCookTimeButton : Button
        {
            public uint CookTime;
        }
    }
}
