## Static recipes

- type: latheRecipePack
  id: StarlightSecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: StarlightSecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - MagazineBoxLightRiflePractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxCaselessRiflePractice
  - MagazineBoxRiflePractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - MagazineDMRPractice

- type: latheRecipePack
  id: StarlightSecurityAmmoEmagStatic
  recipes:
  - L6SawMagazine

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: StarlightSecurityAmmoStatic
  recipes:
######################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleSP
  - MagazineBoxLightRifleHP
  - MagazineBoxLightRifleFMJ
# Magnum
  - MagazineBoxMagnumSP
  - MagazineBoxMagnumHP
  - MagazineBoxMagnumFMJ
# Pistol
  - MagazineBoxCaselessRifle
  - MagazineBoxCaselessRifleRubber
  - MagazineBoxPistolSP
  - MagazineBoxPistolHP
  - MagazineBoxPistolFMJ
  - MagazineBoxPistol40SP
  - MagazineBoxPistol40HP
  - MagazineBoxPistol40FMJ
# Rifle
  - MagazineBoxRifleSP
  - MagazineBoxRifleHP
  - MagazineBoxRifleFMJ
# Shotgun
  - BoxLethalshot
  - BoxShotgunSlug
  - BoxShellTranquilizer
# Battery
  - MagazineBoxBattery
#####################MAGAZINE#######################
# Light Rifle
  - MagazineLightRifleSP
  - MagazineLightRifleHP
  - MagazineLightRifleFMJ
  - MagazineLightRifleMaxim
  - SpeedLoaderLightRifle
  - MagazineLightRifleEmpty
  - MagazineDMRSP
  - MagazineDMRHP
  - MagazineDMRFMJ
  - MagazineDMREmpty
# Magnum
  - SpeedLoaderMagnumSP
  - SpeedLoaderMagnumHP
  - SpeedLoaderMagnumFMJ
  - MagazineMagnum
  - MagazineMagnumRifleSP
  - MagazineMagnumEmpty
  - SpeedLoaderMagnumEmpty
# Pistol
  - MagazinePistolCaselessRifle
  - MagazineCaselessRifleRubber
  - MagazinePistolSP
  - MagazinePistolHP
  - MagazinePistolFMJ
  - MagazinePistolEmpty
  - MagazinePistol40SP
  - MagazinePistol40HP
  - MagazinePistol40FMJ
  - MagazinePistol40Empty
# SMG
  - MagazinePistolSubMachineGunSP
  - MagazinePistolSubMachineGunHP
  - MagazinePistolSubMachineGunFMJ
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazinePistolSubMachineGunUzi
  - MagazinePistolSubMachineGunPPSH
# Rifle
  - MagazineRifleSP
  - MagazineRifleHP
  - MagazineRifleFMJ
  - MagazineRifleEmpty
# Shotgun
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  - SpeedLoaderMagnumBasic
  - SpeedLoaderShotgunEmpty
  - SpeedLoaderShotgunSlug
  - SpeedLoaderShotgunBeanbag
# Battery
  - MagazineBatteryLr30
# Peacekeeper
  - BoxPeacekeeperGas
  - BoxPeacekeeperStinger
  - BoxPeacekeeperFlash
  - BoxPeacekeeperBaton
####################################################

- type: latheRecipePack
  id: StarlightSecurityEmagWeaponsStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: StarlightDefenseStatic
  recipes:
  - EnergyDomeTurtle

- type: latheRecipePack
  id: StarlightSecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield

- type: latheRecipePack
  id: StarlightSecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard
  - ScanGateMachineCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: StarlightSecurityExplosives
  recipes:
  - CableDetStack1
  - EmptyDetonator
  - ExplosivePayload
  - GrenadeBaton
  - GrenadeBlast
  - GrenadeEMP
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: StarlightSecurityAmmoDynamic
  recipes:
#####################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleRubber
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleDragon
  - MagazineBoxLightRifleUranium
  - MagazineBoxLightRifleAP
# Magnum
  - MagazineBoxMagnumRubber
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumDragon
  - MagazineBoxMagnumUranium
  - MagazineBoxMagnumAP
# Pistol
  - MagazineBoxPistolRubber
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolDragon
  - MagazineBoxPistolUranium
  - MagazineBoxPistolAP
  - MagazineBoxPistol40AP
# Rifle
  - MagazineBoxRifleRubber
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleDragon
  - MagazineBoxRifleUranium
  - MagazineBoxRifleAP
# Shotgun
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunDragon
  - BoxShotgunUranium
  - BoxShellTranquilizer
#####################MAGAZINE#######################
# Light Rifle
  - MagazineLightRifleIncendiary
  - MagazineLightRifleDragon
  - MagazineLightRifleUranium
  - MagazineLightRifleAP
  - MagazineDMRIncendiary
  - MagazineDMRDragon
  - MagazineDMRUranium
  - MagazineDMRAP
# Magnum
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumDragon
  - SpeedLoaderMagnumUranium
  - SpeedLoaderMagnumAP
# Pistol
  - MagazinePistolIncendiary
  - MagazinePistolDragon
  - MagazinePistolUranium
  - MagazinePistolAP
  - MagazinePistol40AP
# SMG
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunDragon
  - MagazinePistolSubMachineGunUranium
  - MagazinePistolSubMachineGunAP
# Rifle
  - MagazineRifleIncendiary
  - MagazineRifleDragon
  - MagazineRifleUranium
  - MagazineRifleAP
# Shotgun
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - MagazineShotgunDragon
  - SpeedLoaderShotgunIncendiary
  - SpeedLoaderShotgunDragon
  - SpeedLoaderShotgunUranium
# Grenade
  - MagazineGrenadeEmpty
#####################CARTRIDGE######################
# Light Rifle
  - CartridgeLightRifleRubber
# Magnum
  - CartridgeMagnumRubber
# Pistol
  - CartridgePistolRubber
# Rifle
  - CartridgeRifleRubber
####################################################

- type: latheRecipePack
  id: StarlightSecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  - WeaponIonRifle
  - WeaponIonCarbine
  - WeaponDecloner
  - WeaponLaserImmolator
  - WeaponLaserSvalinn
  - WeaponTemperatureGun
  - FiringPinLaser

- type: latheRecipePack
  id: StarlightSecurityMechsWeapons
  recipes:
  - WeaponMechCombatMissileRack8
  - WeaponMechCombatShotgun
  - WeaponMechCombatShotgunIncendiary
  - WeaponMechCombatUltraRifle
  - WeaponMechCombatXray
  - WeaponMechChainSword
  - WeaponMechCombatIon
  - WeaponMechCombatAMLG90
  - WeaponMechCombatDisabler
  - WeaponMechCombatFlashbangLauncher
  - WeaponMechCombatTaser
  - WeaponMechCombatImmolationGun
  - WeaponMechCombatSolarisLaser
  - WeaponMechCombatFiredartLaser

- type: latheRecipePack
  id: StarlightSecurityMechsSystems
  recipes:
  - MechEquipmentSecGrabber

- type: latheRecipePack
  id: StarlightSecurityMechs
  recipes:
  - GygaxHarness
  - GygaxArmor
  - GygaxHead
  - GygaxLArm
  - GygaxLLeg
  - GygaxRArm
  - GygaxRLeg
  - GygaxCentralElectronics
  - GygaxPeripheralsElectronics
  - GygaxTargetingElectronics

  - DurandHarness
  - DurandArmor
  - DurandHead
  - DurandLArm
  - DurandLLeg
  - DurandRArm
  - DurandRLeg
  - DurandCentralElectronics
  - DurandPeripheralsElectronics
  - DurandTargetingElectronics

- type: latheRecipePack
  id: SecurityCyberLimbs
  recipes:
  - LeftArmCyberBulwark
  - RightArmCyberBulwark
  - LeftArmCyberZeus
  - RightArmCyberZeus
  - LeftArmCyberHerakles
  - RightArmCyberHerakles

- type: latheRecipePack
  id: StarlightSecurityGrenadesEmag
  recipes:
  - GrenadeFrag

- type: latheRecipePack
  id: SecurityImplants
  recipes:
  - HandImplantClaws
  - HandImplantForensics
