- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: true # Starlight - allow setting pref for ninja
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]
  # Starlight start
  previewStartingGear: SpaceNinjaGear
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 3h
  playTimeTracker: AntagNinja
  # Starlight end

#Ninja Gear
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSatchelNinja
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: NinjaPDA
    ears: ClothingHeadsetAssistantNinja # Starlight
    pocket1: SpiderCharge
    pocket2: PinpointerStation
    belt: EnergyKatana
  inhand:
    - JetpackBlackFilled
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - Crowbar
    - Wrench
    - Screwdriver
    - Wirecutter
    - Welder
    - Multitool
    - EmergencyMedipen
    - Flare
    - FoodSnackNutribrick
    - DrinkWaterBottleFull

- type: chameleonOutfit
  id: NinjaChameleonOutfit
  name: roles-antag-space-ninja-name
  icon: "JobIconNinja"
  startingGear: SpaceNinjaGear
  equipment:
    neck: ClothingNeckGoldmedal
