- type: antag
  id: MothershipCore
  name: roles-antag-mothership-core-name
  antagonist: true
  setPreference: true
  objective: roles-antag-mothership-core-objective
  roleLoadout: [ AntagMothership ] # Starlight
  requirements:
  - !type:RoleTimeRequirement
    role: JobStationAi # Starlight
    time: 18000  # 5 hrs
  - !type:RoleTimeRequirement # Starlight
    role: JobRoboticist # Starlight
    time: 9000 # 2.5 hrs
  guides: [ Xenoborgs ]
  playTimeTracker: AntagMothershipCore # Starlight

- type: antag
  id: Xenoborg
  name: roles-antag-xenoborg-name
  antagonist: true
  setPreference: true
  objective: roles-antag-xenoborg-objective
  roleLoadout: [ AntagXenoborg ] # Starlight
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 54000  # Starlight 15 hrs
  guides: [ Xenoborgs ]
  playTimeTracker: AntagXenoborg # Starlight
