using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Guidebook.Richtext;
using Content.Shared.Chemistry.Reagent;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding a reagent into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideReagentGroupEmbed : BoxContainer, IDocumentTag
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    // Starlight
    private List<ReagentPrototype>? _reagentsToAdd;

    public GuideReagentGroupEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.reagent_group");
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideReagentGroupEmbed(string group) : this()
    {
        var prototypes = _prototype.EnumeratePrototypes<ReagentPrototype>()
            .Where(p => p.Group.Equals(group)).OrderBy(p => p.LocalizedName);
        _reagentsToAdd = prototypes.ToList(); // Starlight
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Group", out var group))
        {
            _sawmill.Error("Reagent group embed tag is missing group argument");
            return false;
        }

        var prototypes = _prototype.EnumeratePrototypes<ReagentPrototype>()
            .Where(p => p.Group.Equals(group)).OrderBy(p => p.LocalizedName);
        _reagentsToAdd = prototypes.ToList(); // Starlight

        control = this;
        return true;
    }

    // Starlight
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_reagentsToAdd == null)
            return;

        // Stop after adding 5 reagents, wait for next frame update
        // This prevents it from lagging as much, and helps to not trigger
        // the style update limit in engine
        var count = _reagentsToAdd.Count;
        for (var i = count - 1; i >= Math.Max(0, count - 5); i--)
        {
            var reagent = _reagentsToAdd[i];
            _reagentsToAdd.RemoveAt(i);
            var embed = new GuideReagentEmbed(reagent);
            GroupContainer.AddChild(embed);
        }
    }
}
