using Content.Client._DV.CustomObjectiveSummary;
using Content.Client._Moffstation.ObjectivePicker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CharacterMenu;

[GenerateTypedNameReferences]
public sealed partial class MoffCharacterWindow : DefaultWindow
{
    public MoffCharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddObjectiveButtons(int objectiveCount, bool canPickObjectives)
    {
        // Reset what the button does
        ObjectiveButton.OnPressed -= CustomObjectiveButtonPressed;
        ObjectiveButton.OnPressed -= ObjectivePickerButtonPressed;

        // No objectives label
        if (!canPickObjectives)
        {
            // Pinktexting
            if (objectiveCount <= 0)
            {
                ObjectiveButton.Visible = false;
                NoObjectivesLabel.Visible = true;
                return;
            }

            ObjectiveButton.Visible = true;
            NoObjectivesLabel.Visible = false;
            ObjectiveButton.OnPressed += CustomObjectiveButtonPressed;
            ObjectiveButton.Text = Loc.GetString("custom-objective-button-text");
        }
        else
        {
            ObjectiveButton.Visible = true;
            NoObjectivesLabel.Visible = false;

            // Objective picker button
            ObjectiveButton.OnPressed += ObjectivePickerButtonPressed;
            ObjectiveButton.Text = Loc.GetString("objective-picker-button");
        }
    }

    private void CustomObjectiveButtonPressed(BaseButton.ButtonEventArgs args)
    {
        UserInterfaceManager.GetUIController<CustomObjectiveSummaryUIController>().OpenWindow();
    }

    private void ObjectivePickerButtonPressed(BaseButton.ButtonEventArgs args)
    {
        UserInterfaceManager.GetUIController<ObjectivePickerUIController>().EnsureWindow();
    }
}
