using Content.Client._DV.CustomObjectiveSummary;
using Content.Client._Moffstation.ObjectivePicker;
using Content.Client.Stylesheets.Palette;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.CharacterMenu;

[GenerateTypedNameReferences]
public sealed partial class MoffCharacterWindow : DefaultWindow
{
    private const float PulseSpeed = 2.5f;
    private float _pulseTime;
    private bool _pulseEnabled;

    // This is a bit weird but *should* expose the green used for the button press... it feels gross though
    private static readonly Color PulseGreen = Palettes.Green.Element;

    public MoffCharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_pulseEnabled || !ObjectiveButton.Visible)
        {
            ObjectiveButton.ModulateSelfOverride = null;
            return;
        }

        if (!ObjectiveButton.TryGetStyleProperty(StylePropertyModulateSelf, out Color buttonColor))
            return;

        var delta = (MathF.Sin(_pulseTime * PulseSpeed) + 1f) / 2f;
        _pulseTime += args.DeltaSeconds;
        ObjectiveButton.ModulateSelfOverride = Color.InterpolateBetween(buttonColor, PulseGreen, delta);
    }

    public void AddObjectiveButtons(int objectiveCount, bool canPickObjectives)
    {
        _pulseEnabled = canPickObjectives;

        // Reset what the button does
        ObjectiveButton.OnPressed -= CustomObjectiveButtonPressed;
        ObjectiveButton.OnPressed -= ObjectivePickerButtonPressed;

        // No objectives label
        if (!canPickObjectives)
        {
            // Pinktexting
            if (objectiveCount <= 0)
            {
                ObjectiveButton.Visible = false;
                NoObjectivesLabel.Visible = true;
                return;
            }

            ObjectiveButton.Visible = true;
            NoObjectivesLabel.Visible = false;
            ObjectiveButton.OnPressed += CustomObjectiveButtonPressed;
            ObjectiveButton.Text = Loc.GetString("custom-objective-button-text");
        }
        else
        {
            ObjectiveButton.Visible = true;
            NoObjectivesLabel.Visible = false;

            // Objective picker button
            ObjectiveButton.OnPressed += ObjectivePickerButtonPressed;
            ObjectiveButton.Text = Loc.GetString("objective-picker-button");
        }
    }

    private void CustomObjectiveButtonPressed(BaseButton.ButtonEventArgs args)
    {
        UserInterfaceManager.GetUIController<CustomObjectiveSummaryUIController>().OpenWindow();
    }

    private void ObjectivePickerButtonPressed(BaseButton.ButtonEventArgs args)
    {
        UserInterfaceManager.GetUIController<ObjectivePickerUIController>().EnsureWindow();
    }
}
