using Content.Shared._Starlight.Traits;
using Content.Shared._Starlight.Traits.Effects;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterBackgroundInfoControl : Control
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public CharacterBackgroundInfoControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid? viewer = null)
    {
        if (!target.HasValue)
        {
            ClearCharacter();
            return;
        }
        BackgroundLabel.Text = Loc.GetString("character-info-background-none");
        Background.Text = null;

        if (!entityManager.TryGetComponent<TagComponent>(target, out var comp))
            return;

        var backgrounds = new List<string>();

        foreach (var tag in comp.Tags)
        {
            if (!tag.Id.EndsWith("TraitBackground", StringComparison.Ordinal))
                continue;

            if (!TryGetBackgroundName(tag, out var name))
                continue;

            backgrounds.Add(Loc.GetString(name));
        }

        if (backgrounds.Count > 0)
        {
            backgrounds.Sort(StringComparer.CurrentCulture);
            BackgroundLabel.Text = Loc.GetString("character-info-background-label");
            Background.Text = string.Join(", ", backgrounds);
        }
    }

    private bool TryGetBackgroundName(ProtoId<TagPrototype> tag, out LocId name)
    {
        foreach (var trait in _prototypeManager.EnumeratePrototypes<TraitPrototype>())
        {
            foreach (var effect in trait.Effects)
            {
                if (effect is BackgroundEffect background && background.Background + "TraitBackground" == tag.Id)
                {
                    name = trait.Name;
                    return true;
                }
            }
        }

        name = default;
        return false;
    }

    public void ClearCharacter()
    {
        BackgroundLabel.Text = Loc.GetString("character-info-background-none");
        Background.Text = null;
    }
}
