using Content.Client.Stylesheets.Palette;
using Content.Client._Starlight.CustomObjectiveSummary;
using Content.Client._Starlight.Objectives.ObjectivePicker;
using Content.Client._Starlight.Railroading;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class SLCharacterWindow : DefaultWindow
{
    private const float PulseSpeed = 2.5f;
    private float _pulseTime;
    private bool _pulseEnabled;

    // This is a bit weird but *should* expose the green used for the button press... it feels gross though
    private static readonly Color _pulseGreen = Palettes.Green.Element;

    public SLCharacterWindow()
    {
        RobustXamlLoader.Load(this);
        SLInitializeCharacterInfo();
        CardsButton.OnPressed += _ => UserInterfaceManager.GetUIController<CardsUIController>().OpenCards();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        CardsButton.Modulate = UserInterfaceManager.GetUIController<CardsUIController>().PulseModulate;

        if (!_pulseEnabled || !ObjectiveButton.Visible)
        {
            ObjectiveButton.ModulateSelfOverride = null;
            return;
        }

        if (!ObjectiveButton.TryGetStyleProperty(StylePropertyModulateSelf, out Color buttonColor))
            return;

        var delta = (MathF.Sin(_pulseTime * PulseSpeed) + 1f) / 2f;
        _pulseTime += args.DeltaSeconds;
        ObjectiveButton.ModulateSelfOverride = Color.InterpolateBetween(buttonColor, _pulseGreen, delta);
    }

    public void AddObjectiveButtons(int objectiveCount, bool canPickObjectives, bool canPickMore = false)
    {
        var showPicker = canPickObjectives || canPickMore;
        _pulseEnabled = showPicker;
        CardsButton.SetPositionInParent(showPicker ? 1 : 0);

        // Reset what the button does
        ObjectiveButton.OnPressed -= CustomObjectiveButtonPressed;
        ObjectiveButton.OnPressed -= ObjectivePickerButtonPressed;

        // No objectives label
        if (!showPicker)
        {
            // Pinktexting
            if (objectiveCount <= 0)
            {
                ObjectiveButton.Visible = false;
                NoObjectivesLabel.Visible = true;
                return;
            }

            ObjectiveButton.Visible = true;
            NoObjectivesLabel.Visible = false;
            ObjectiveButton.OnPressed += CustomObjectiveButtonPressed;
            ObjectiveButton.Text = Loc.GetString("custom-objective-button-text");
        }
        else
        {
            ObjectiveButton.Visible = true;
            NoObjectivesLabel.Visible = false;

            // Objective picker button
            ObjectiveButton.OnPressed += ObjectivePickerButtonPressed;
            ObjectiveButton.Text = Loc.GetString(canPickMore ? "objective-picker-additional-button" : "objective-picker-button");
        }
    }

    private void CustomObjectiveButtonPressed(BaseButton.ButtonEventArgs args) => UserInterfaceManager.GetUIController<CustomObjectiveSummaryUIController>().OpenWindow();

    private void ObjectivePickerButtonPressed(BaseButton.ButtonEventArgs args) => UserInterfaceManager.GetUIController<ObjectivePickerUIController>().OpenPicker();

    private void SLInitializeCharacterInfo()
    {
        CharacterInfoTabs.SetTabTitle(0, Loc.GetString("character-info-objectives"));
        CharacterInfoTabs.SetTabTitle(1, Loc.GetString("character-info-ic-ooc"));

        // The overview already displays the character's sprite and identity.
        InfoIC.CharacterView.Visible = false;
        InfoOOC.CharacterView.Visible = false;
    }
}
