using Content.Client.GameTicking.Managers;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Text.RegularExpressions; // Starlight

namespace Content.Client.Store.Ui;

[GenerateTypedNameReferences]
public sealed partial class StoreListingControl : Control
{
    public event Action<string, string>? OnListingHoverEntered; // Starlight
    public event Action? OnListingHoverExited; // Starlight
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly ClientGameTicker _ticker;

    private readonly ListingDataWithCostModifiers _data;

    private static readonly Regex _priceNumberRegex = new("([0-9]+(?:[.,][0-9]+)?)", RegexOptions.Compiled); // Starlight

    private readonly bool _hasBalance;
    private readonly string _price;
    private readonly string _discount;
    private readonly bool _compact; // Starlight
    public StoreListingControl(ListingDataWithCostModifiers data, string price, string discount, bool hasBalance, Texture? texture = null, bool compact = false) // Starlight
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _ticker = _entity.System<ClientGameTicker>();

        _data = data;
        _hasBalance = hasBalance;
        _price = price;
        _discount = discount;
        _compact = compact; // Starlight

        StoreItemName.Text = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        StoreItemDescription.SetMessage(ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));

        if (_compact) // Starlight
        {
            StoreItemName.Visible = false;
            StoreItemDescription.Visible = false;
            DiscountSubText.Visible = false;
            StoreItemBuyButton.HorizontalAlignment = Robust.Client.UserInterface.Control.HAlignment.Center;
            StoreItemBuyButton.HorizontalExpand = false;
        }

        UpdateBuyButtonText();
        StoreItemBuyButton.Disabled = !CanBuy();

        StoreItemTexture.Texture = texture;
    // Starlight start
    OnMouseEntered += _ => OnListingHoverEntered?.Invoke(ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype), ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));
    OnMouseExited += _ => OnListingHoverExited?.Invoke();

    StoreItemTexture.OnMouseEntered += _ => OnListingHoverEntered?.Invoke(ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype), ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));
    StoreItemTexture.OnMouseExited += _ => OnListingHoverExited?.Invoke();

    StoreItemBuyButton.OnMouseEntered += _ => OnListingHoverEntered?.Invoke(ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype), ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));
    StoreItemBuyButton.OnMouseExited += _ => OnListingHoverExited?.Invoke();
    // Starlight end
    }

    private bool CanBuy()
    {
        if (!_hasBalance)
            return false;

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
            return false;

        // Starlight: Check if the listing is marked as unavailable (e.g., when a rift is active or out of stock)
        if (_data.Unavailable)
            return false;
        // Starlight End

        return true;
    }

    private void UpdateBuyButtonText()
    {
        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            var timeLeftToBuy = stationTime - _data.RestockTime;
            StoreItemBuyButton.Text =  timeLeftToBuy.Duration().ToString(@"mm\:ss");
        }
        else
        {
            DiscountSubText.Text = _discount;
            if (_compact) // Starlight start
            {
                // Can be done better
                var m = _priceNumberRegex.Match(_price);
                if (m.Success)
                {
                    StoreItemBuyButton.Text = $"{m.Groups[1].Value}¢";
                }
                else
                {
                    StoreItemBuyButton.Text = _price;
                }
            }
            else
            {
                StoreItemBuyButton.Text = _price;
            } // Starlight end
        }
    }

    // Starlight
    private void UpdateNameAndDescription()
    {
        // Get the localized name, which will already include stock count or "Out of Stock" text
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        StoreItemName.Text = name;

        // Get the localized description, which will include the last purchaser information
        var description = ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype);
        StoreItemDescription.SetMessage(description);
    }
    // Starlight End
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateBuyButtonText();
        UpdateNameAndDescription(); // Starlight
        StoreItemBuyButton.Disabled = !CanBuy();
    }
}
