using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Objectives;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.ObjectivePicker;

[GenerateTypedNameReferences]
public sealed partial class ObjectivePickerWindow : FancyWindow
{
    [Dependency] private IPlayerManager _players = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly SpriteSystem _sprite;
    private readonly SharedMindSystem _mind;

    private float _updateTimer = 1.0f;
    private const float UpdateRate = 1.0f;

    public event Action<NetEntity>? OnSelectedChange;
    public event Action<HashSet<NetEntity>, NetEntity>? OnSubmitted;
    public event Action? OnRandomize; // Starlight, randomization uses the difficulty budget.
    public event Action? OnClear;

    public readonly HashSet<NetEntity> SelectedObjectives = [];

    public ObjectivePickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mind = _entity.System<SharedMindSystem>();
        _sprite = _entity.System<SpriteSystem>();

        SLInitializePicker(); // Starlight
    }

    private void PopulateObjectives(EntityUid mindUid) => SLPopulateObjectives(mindUid); // Starlight

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer += args.DeltaSeconds;

        if (_updateTimer >= UpdateRate)
        {
            _updateTimer -= UpdateRate;
            UpdateTimer();
        }
    }

    public void UpdateState()
    {
        _mind.TryGetMind(_players.LocalSession, out var mindUid, out _);
        PopulateObjectives(mindUid);
    }

    private void UpdateTimer() => SLUpdateTimer(); // Starlight
}
